kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    commands:
      - go version
      - pwd
      - git clone git://github.com/mqzhifu/zgoframe.git
      - ls -l
      - cd zgoframe
      - ls -l
      - go mod tidy
      - gp run main.go -e test -dep 1



