kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      PROJECT_NAME: zgoframe
      TARGET_GIT_PROJECT_DIR: /www/git_project
      ENV: test
      KNOWN_HOST_202:
        from_secret: KNOWN_HOST_202
      ID_RSA_202:
        from_secret: ID_RSA_202
    commands:
      - id
      - echo $ID_RAS
      - mkdir -p /root/.ssh
      - echo "$KNOWN_HOST_202" > /root/.ssh/known_hosts
      - echo "$ID_RSA_202" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa && chmod 700 /root/.ssh

      - pwd
      - go version
      - git clone git://github.com/mqzhifu/$PROJECT_NAME.git
      - ls -l
      - cd $PROJECT_NAME
      - ls -l

      - date
      - export CI_COMMIT_TIME=$(git show -s --format=%ct)
      - export CI_COMMIT_TIME_FORMATTED=`TZ='Asia/Shanghai' date -d @"$CI_COMMIT_TIME" "+%Y%m%d_%H%M%S"`
      - export CI_COMMIT_ID=$(git rev-parse --short HEAD)
      - export APP_NAME_FULL="$CI_COMMIT_TIME_FORMATTED-$CI_COMMIT_ID"
      - echo $APP_NAME_FULL

      - rm -rf .git
      - cd ..
      - ls -l
      - scp -r $PROJECT_NAME root@114.116.212.202:$TARGET_GIT_PROJECT_DIR
      - ssh root@114.116.212.202 "ls -l $TARGET_GIT_PROJECT_DIR/$PROJECT_NAME"
      - ssh root@114.116.212.202 "go version"
      - ssh root@114.116.212.202 "go env -w GO111MODULE=on ; go env -w GOPROXY=https://goproxy.cn,direct "
      - ssh root@114.116.212.202 "cd  $TARGET_GIT_PROJECT_DIR/$PROJECT_NAME; go mod tidy ; go mod download"




