kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang
    commands:
      - go version
      - pwd
      - git clone git://github.com/mqzhifu/zgoframe.git


