kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang1.16.2
    commands:
      - go version
      - pwd
      - git clone git://github.com/mqzhifu/zgoframe.git
      - ls -l
      - cd zgoframe
      - ls -l
      - go tidy



