kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    commands:
      - go version
      - pwd
      - git clone git://github.com/mqzhifu/zgoframe.git
      - ls -l
      - cd zgoframe
      - ls -l
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod tidy
      - go mod download
      - cp config.toml.tmp config.toml
      - cat config.toml
      - echo "mkdir logs & chmod 777 logs"
      - mkdir logs
      - chmod 777 logs
      - go run main.go -e test -dep 1



