kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      ENV: test
      PROJECT_NAME: zgoframe
      TARGET_GIT_PROJECT_DIR: /www/git_project
      TARGET_GIT_PROJECT_BUILD_ORI_DIR: $TARGET_GIT_PROJECT_DIR/$PROJECT_NAME
      GIT_ORI_URL: git://github.com/mqzhifu

      KNOWN_HOST_202:
        from_secret: KNOWN_HOST_202
      ID_RSA_202:
        from_secret: ID_RSA_202
    commands:
      - id
      - echo "$ENV $GIT_ORI_URL  $PROJECT_NAME $TARGET_GIT_PROJECT_DIR $TARGET_GIT_PROJECT_BUILD_ORI_DIR"
      - mkdir -p /root/.ssh
      - echo "$KNOWN_HOST_202" > /root/.ssh/known_hosts
      - echo "$ID_RSA_202" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa && chmod 700 /root/.ssh

      - pwd
      - go version
      - git clone $GIT_ORI_URL/$PROJECT_NAME.git
      - ls -l
      - cd $PROJECT_NAME
      - ls -l

      - date
      - export CI_COMMIT_TIME=$(git show -s --format=%ct)
      - export CI_COMMIT_TIME_FORMATTED=`TZ='Asia/Shanghai' date -d @"$CI_COMMIT_TIME" "+%Y%m%d_%H%M%S"`
      - export CI_COMMIT_ID=$(git rev-parse --short HEAD)
      - export APP_NAME_FULL="$CI_COMMIT_TIME_FORMATTED-$CI_COMMIT_ID"
      - echo $APP_NAME_FULL

      - rm -rf .git
      - cd ..;ls -l
      -
      -
      - ssh root@"$CN_DEV_HOST" "if [ -f $TARGET_GIT_PROJECT_BUILD_ORI_DIR ]; then mkdir $TARGET_GIT_PROJECT_BUILD_ORI_DIR; chmod 777 $TARGET_GIT_PROJECT_BUILD_ORI_DIR; fi;"
      - export BUILD_DIR=$TARGET_GIT_PROJECT_BUILD_ORI_DIR$APP_NAME_FULL
      - echo "BUILD_DIR:$BUILD_DIR"







