kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      PROJECT_NAME: zgoframe
      ENV: test
      KNOWN_HOST_202:
        from_secret: KNOWN_HOST_202
      ID_RSA_202:
        from_secret: ID_RSA_202
    commands:
      - id
      - echo $ID_RAS
      - mkdir -p /root/.ssh
      - echo "$KNOWN_HOST_202" > /root/.ssh/known_hosts
      - echo "$ID_RSA_202" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa && chmod 700 /root/.ssh

      - pwd
      - go version
      - git clone git://github.com/mqzhifu/$PROJECT_NAME.git
      - ls -l
      - cd $PROJECT_NAME
      - ls -l

      - export CI_COMMIT_TIME=$(git show -s --format=%ct)
      - export CI_COMMIT_TIME_FORMATTED=`TZ='WAUST-8WAUDT' date -d @"$CI_COMMIT_TIME" "+%Y%m%dT%H%M%S"`
      - export CI_COMMIT_ID=$(git rev-parse --short HEAD)
      - export APP_NAME_FULL="$CI_COMMIT_TIME_FORMATTED-$CI_COMMIT_ID"
      - echo $APP_NAME_FULL

      - cd ..
      - ls -l




