kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      ENV: test
      KNOWN_HOST_202: 114.116.212.202 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOdyMWzDditH6hBI3BrB13VTxDMo9BZfICToB5kQDss1C0gLGuJxQNl97tDvzJ0I/g2VY4GJNJOxTJhdoC4Rgkw=
      ID_RAS:
        from_secret: ID_RSA_202
    commands:
      - go version
      - id
      - echo $ID_RAS
      - mkdir -p /root/.ssh
      - echo "$KNOWN_HOST_202" > /root/.ssh/known_hosts
      - echo "$ID_RAS" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa && chmod 700 /root/.ssh
      - ssh root@114.116.212.202 "ls -l /www"


