kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      ENV: test
    commands:


      - ssh root@"$SERVER_HOST" "ps aux|grep zgoframe|grep -v grep|awk '{print $2}'|xargs kill"
      - sleep 1
      - ssh root@"$SERVER_HOST" "$PROJECT_DIR_FINAL/$PROJECT_NAME -e test
      - echo "process exec ok~"










