kind: pipeline
name: default-frame

clone:
  disable: true

steps:
  - name: test
    image: golang:1.16.2
    environment:
      ENV: test
    commands:

  - ssh root@"$SERVER_HOST" "if [ $(ps -ef |grep $PROJECT_NAME|grep -v grep|wc -l) -gt 0 ];then echo processexist-need kill ;else echo process-not-exist;fi"

      - ssh root@"$SERVER_HOST" "ps aux|grep zgoframe|grep -v grep|awk '{print $2}'|xargs kill"
      - sleep 1











