#当前项目的CICD配置信息
[system]
startup = "#master_path#/#service_name# -e #env#"
listeningPorts = "3306,3308"
testUnit = "go run test"
build = "go build -ldflags  \"-X main.BuildGitVersion='#git_version#' -X main.BuildTime='#datetime#' \" -o #service_name#"
#build = "go build -ldflags \"-X main.BuildGitVersion='#git_version#' -X 'main.BUILD_TIME=`#datetime#`' \" -o #service_name#"
command="go version;go env -w GO111MODULE=on;go env -w GOPROXY=https://goproxy.cn,direct;go mod tidy;go mod download;go get -u github.com/swaggo/swag/cmd/swag@v1.7.9;$HOME/go/bin/swag init --parseDependency --parseInternal --parseDepth 3;"
configTmpFileName="config.toml.tmp"
configFileName="config.toml"


[depend]
go="1.16"
mysql="5.5"
redis="3.0"

