#当前项目的CICD配置信息
[system]
startup = "go run main.go -e #env#"
listeningPorts = "3306,3308"
testUnit = "go run test"
build = "go build -o #service_name#"
command="go mod tidy"
configTmpFileName="config.toml.tmp"
configFileName="config.toml"

[depend]
go="1.16"
mysql="5.5"
redis="3.0"

