[system]
env=["local","dev","test","pre","online"]

#本机/远端，目录
logDir="/data/logs/www"
#本机进行cicd部署时的：根目录
workBaseDir= "/data/www/cicd"
#本地部署成功后，会往远端同步代码，这里是远端服务器存放代码的目录
remoteBaseDir = "/data/www"
remoteUploadDir = "/data/file_upload"

masterDirName = "master"
gitCloneTmpDirName="clone"
httpPort="4455"


[superVisor]
rpcPort="9001"
#confTemplateFile="/data/www/golang/src/zgoframe/operation/super_visor.ini" #暂时用相对路径，方便CICD
confTemplateFile="super_visor.ini"
confDir="/etc/supervisord.d"



