[system]
env=["local","dev","test","pre","online"]

logDir="/data/www/golang/testcicd/logs"
workBaseDir= "/data/www/golang/testcicd"
#serviceDir="/data/www/golang/testcicd"
#localServiceDir="/data/www/golang/testcicd/local"
#serviceMasterName="master"
masterDirName = "master"
gitCloneTmpDirName="clone"
httpPort="4455"

[superVisor]
rpcPort="9001"
confTemplateFile="/data/www/golang/src/zgoframe/operation/super_visor.ini"
confDir="/etc/supervisord.d"



