#[system]
#env=["local","dev","test","pre","online"]
#
##本机/远端，目录
#logDir="/data/logs/cicd"
##本机进行cicd部署时的：根目录
#workBaseDir= "/data/cicd"
##本地部署成功后，会往远端同步代码，这里是远端服务器存放代码的目录
#remoteBaseDir = "/opt/cicd"
#remoteUploadDir = "/opt/cicd/file_upload"
#remoteDownloadDir = "/opt/cicd/file_download"
#
#masterDirName = "master"
#gitCloneTmpDirName="clone"
#httpPort="4455"
#
#
#
