[system]
env=["local","dev","test","pre","online"]

logDir="/data/www/golang/testcicd/logs"
workBaseDir= "/data/www/golang/testcicd"

masterDirName = "master"
gitCloneTmpDirName="clone"
httpPort="4455"

#serviceDir="/data/www/golang/testcicd"
#localServiceDir="/data/www/golang/testcicd/local"
#serviceMasterName="master"

[superVisor]
rpcPort="9001"
confTemplateFile="super_visor.ini"
confDir="/etc/supervisord.d"



