// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//有些函数，没有返回值，统一定义一个，方便处理
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

//心跳，长连接保活。(不要与PING混淆)
type Heartbeat struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type FDCloseEvent struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source               int32    `protobuf:"varint,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FDCloseEvent) Reset()         { *m = FDCloseEvent{} }
func (m *FDCloseEvent) String() string { return proto.CompactTextString(m) }
func (*FDCloseEvent) ProtoMessage()    {}
func (*FDCloseEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *FDCloseEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FDCloseEvent.Unmarshal(m, b)
}
func (m *FDCloseEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FDCloseEvent.Marshal(b, m, deterministic)
}
func (m *FDCloseEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FDCloseEvent.Merge(m, src)
}
func (m *FDCloseEvent) XXX_Size() int {
	return xxx_messageInfo_FDCloseEvent.Size(m)
}
func (m *FDCloseEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FDCloseEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FDCloseEvent proto.InternalMessageInfo

func (m *FDCloseEvent) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FDCloseEvent) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

type FDCreateEvent struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FDCreateEvent) Reset()         { *m = FDCreateEvent{} }
func (m *FDCreateEvent) String() string { return proto.CompactTextString(m) }
func (*FDCreateEvent) ProtoMessage()    {}
func (*FDCreateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *FDCreateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FDCreateEvent.Unmarshal(m, b)
}
func (m *FDCreateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FDCreateEvent.Marshal(b, m, deterministic)
}
func (m *FDCreateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FDCreateEvent.Merge(m, src)
}
func (m *FDCreateEvent) XXX_Size() int {
	return xxx_messageInfo_FDCreateEvent.Size(m)
}
func (m *FDCreateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FDCreateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FDCreateEvent proto.InternalMessageInfo

func (m *FDCreateEvent) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PingReq struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId              string   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ClientReqTime        int64    `protobuf:"varint,3,opt,name=client_req_time,json=clientReqTime,proto3" json:"client_req_time,omitempty"`
	ClientReceiveTime    int64    `protobuf:"varint,4,opt,name=client_receive_time,json=clientReceiveTime,proto3" json:"client_receive_time,omitempty"`
	ServerReceiveTime    int64    `protobuf:"varint,5,opt,name=server_receive_time,json=serverReceiveTime,proto3" json:"server_receive_time,omitempty"`
	ServerResponseTime   int64    `protobuf:"varint,6,opt,name=server_response_time,json=serverResponseTime,proto3" json:"server_response_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *PingReq) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *PingReq) GetClientReqTime() int64 {
	if m != nil {
		return m.ClientReqTime
	}
	return 0
}

func (m *PingReq) GetClientReceiveTime() int64 {
	if m != nil {
		return m.ClientReceiveTime
	}
	return 0
}

func (m *PingReq) GetServerReceiveTime() int64 {
	if m != nil {
		return m.ServerReceiveTime
	}
	return 0
}

func (m *PingReq) GetServerResponseTime() int64 {
	if m != nil {
		return m.ServerResponseTime
	}
	return 0
}

type PongRes struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId              string   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ClientReqTime        int64    `protobuf:"varint,3,opt,name=client_req_time,json=clientReqTime,proto3" json:"client_req_time,omitempty"`
	ClientReceiveTime    int64    `protobuf:"varint,4,opt,name=client_receive_time,json=clientReceiveTime,proto3" json:"client_receive_time,omitempty"`
	ServerReceiveTime    int64    `protobuf:"varint,5,opt,name=server_receive_time,json=serverReceiveTime,proto3" json:"server_receive_time,omitempty"`
	ServerResponseTime   int64    `protobuf:"varint,6,opt,name=server_response_time,json=serverResponseTime,proto3" json:"server_response_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongRes) Reset()         { *m = PongRes{} }
func (m *PongRes) String() string { return proto.CompactTextString(m) }
func (*PongRes) ProtoMessage()    {}
func (*PongRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *PongRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongRes.Unmarshal(m, b)
}
func (m *PongRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongRes.Marshal(b, m, deterministic)
}
func (m *PongRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongRes.Merge(m, src)
}
func (m *PongRes) XXX_Size() int {
	return xxx_messageInfo_PongRes.Size(m)
}
func (m *PongRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PongRes.DiscardUnknown(m)
}

var xxx_messageInfo_PongRes proto.InternalMessageInfo

func (m *PongRes) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *PongRes) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *PongRes) GetClientReqTime() int64 {
	if m != nil {
		return m.ClientReqTime
	}
	return 0
}

func (m *PongRes) GetClientReceiveTime() int64 {
	if m != nil {
		return m.ClientReceiveTime
	}
	return 0
}

func (m *PongRes) GetServerReceiveTime() int64 {
	if m != nil {
		return m.ServerReceiveTime
	}
	return 0
}

func (m *PongRes) GetServerResponseTime() int64 {
	if m != nil {
		return m.ServerResponseTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Heartbeat)(nil), "pb.Heartbeat")
	proto.RegisterType((*FDCloseEvent)(nil), "pb.FDCloseEvent")
	proto.RegisterType((*FDCreateEvent)(nil), "pb.FDCreateEvent")
	proto.RegisterType((*PingReq)(nil), "pb.PingReq")
	proto.RegisterType((*PongRes)(nil), "pb.PongRes")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0x3f, 0x4b, 0xc4, 0x40,
	0x14, 0xc4, 0x49, 0xee, 0x92, 0x98, 0xc7, 0x1d, 0xe2, 0x2a, 0x7a, 0x16, 0xa2, 0xa4, 0x90, 0xab,
	0xa2, 0x60, 0x69, 0x21, 0x78, 0x7f, 0x30, 0x9d, 0x04, 0x2b, 0x9b, 0x90, 0x3f, 0x0f, 0x59, 0xb8,
	0x64, 0x37, 0xbb, 0x9b, 0x80, 0x1f, 0x5e, 0x90, 0xbc, 0xbd, 0x1c, 0x5a, 0xf9, 0x01, 0xec, 0x76,
	0x66, 0x7e, 0xb3, 0x30, 0xf0, 0x60, 0x56, 0x8a, 0xba, 0x16, 0x4d, 0x2c, 0x95, 0x30, 0x82, 0xb9,
	0xb2, 0x88, 0x02, 0xf0, 0x36, 0xb5, 0x34, 0x9f, 0xd1, 0x35, 0x84, 0x2f, 0x98, 0x2b, 0x53, 0x60,
	0x6e, 0x18, 0x83, 0xa9, 0xe1, 0x35, 0x2e, 0x9c, 0x1b, 0x67, 0x39, 0x49, 0xe9, 0x1d, 0x3d, 0xc1,
	0x6c, 0xbb, 0x5e, 0xed, 0x84, 0xc6, 0x4d, 0x8f, 0x8d, 0x61, 0x17, 0x10, 0x74, 0x1a, 0x55, 0xc6,
	0x2b, 0xc2, 0xbc, 0xd4, 0x1f, 0x64, 0x52, 0xb1, 0x73, 0xf0, 0xb5, 0xe8, 0x54, 0x89, 0x0b, 0xd7,
	0xfa, 0x56, 0x45, 0x4b, 0x98, 0x6f, 0xd7, 0x2b, 0x85, 0xb9, 0xf9, 0xe3, 0x87, 0xe8, 0xcb, 0x81,
	0xe0, 0x95, 0x37, 0x1f, 0x29, 0xb6, 0xec, 0x0a, 0x40, 0x61, 0xdb, 0xa1, 0x36, 0x23, 0x17, 0xa6,
	0xe1, 0xde, 0x49, 0x2a, 0x76, 0x09, 0x47, 0x46, 0xe5, 0x25, 0x0e, 0xa1, 0x4b, 0x61, 0x40, 0x3a,
	0xa9, 0xd8, 0x2d, 0x1c, 0x97, 0x3b, 0x8e, 0x8d, 0xc9, 0x14, 0xb6, 0x19, 0xed, 0x99, 0xd0, 0x9e,
	0xb9, 0xb5, 0x53, 0x6c, 0xdf, 0x78, 0x8d, 0x2c, 0x86, 0xd3, 0x03, 0x57, 0x22, 0xef, 0xd1, 0xb2,
	0x53, 0x62, 0x4f, 0x46, 0x96, 0x92, 0x91, 0xd7, 0xa8, 0x7a, 0x54, 0xbf, 0x79, 0xcf, 0xf2, 0x36,
	0xfa, 0xc9, 0xdf, 0xc3, 0xd9, 0x81, 0xd7, 0x52, 0x34, 0x7a, 0x5f, 0xf0, 0xa9, 0xc0, 0xc6, 0x82,
	0x8d, 0x86, 0x86, 0xdd, 0x2f, 0x86, 0xfd, 0xfa, 0x3f, 0xee, 0x7f, 0x0e, 0xde, 0xbd, 0xf8, 0xee,
	0x51, 0x16, 0x85, 0x4f, 0x87, 0xfa, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xd4, 0x18, 0x49,
	0xb8, 0x02, 0x00, 0x00,
}
