// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	//allow_alias = true;
	PhoneType_mobile PhoneType = 0
	PhoneType_home   PhoneType = 1
	PhoneType_word   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "mobile",
	1: "home",
	2: "word",
}

var PhoneType_value = map[string]int32{
	"mobile": 0,
	"home":   1,
	"word":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{0}
}

type RequestRegPlayer struct {
	AddTime              int32               `protobuf:"varint,1,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"`
	PlayerList           []*Player           `protobuf:"bytes,3,rep,name=player_list,json=playerList,proto3" json:"player_list,omitempty"`
	PlayerInfo           *Player             `protobuf:"bytes,4,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	ChannelMap           map[uint64]*Channel `protobuf:"bytes,5,rep,name=channel_map,json=channelMap,proto3" json:"channel_map,omitempty" protobuf_key:"fixed64,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RequestRegPlayer) Reset()         { *m = RequestRegPlayer{} }
func (m *RequestRegPlayer) String() string { return proto.CompactTextString(m) }
func (*RequestRegPlayer) ProtoMessage()    {}
func (*RequestRegPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{0}
}

func (m *RequestRegPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRegPlayer.Unmarshal(m, b)
}
func (m *RequestRegPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRegPlayer.Marshal(b, m, deterministic)
}
func (m *RequestRegPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRegPlayer.Merge(m, src)
}
func (m *RequestRegPlayer) XXX_Size() int {
	return xxx_messageInfo_RequestRegPlayer.Size(m)
}
func (m *RequestRegPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRegPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRegPlayer proto.InternalMessageInfo

func (m *RequestRegPlayer) GetAddTime() int32 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *RequestRegPlayer) GetPlayerList() []*Player {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

func (m *RequestRegPlayer) GetPlayerInfo() *Player {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *RequestRegPlayer) GetChannelMap() map[uint64]*Channel {
	if m != nil {
		return m.ChannelMap
	}
	return nil
}

type Player struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName             []byte    `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Nickname             string    `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status               uint32    `protobuf:"fixed32,4,opt,name=status,proto3" json:"status,omitempty"`
	Score                float32   `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	PhoneType            PhoneType `protobuf:"varint,6,opt,name=phone_type,json=phoneType,proto3,enum=pb.PhoneType" json:"phone_type,omitempty"`
	Sex                  bool      `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Level                int32     `protobuf:"zigzag32,8,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetRoleName() []byte {
	if m != nil {
		return m.RoleName
	}
	return nil
}

func (m *Player) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Player) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Player) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Player) GetPhoneType() PhoneType {
	if m != nil {
		return m.PhoneType
	}
	return PhoneType_mobile
}

func (m *Player) GetSex() bool {
	if m != nil {
		return m.Sex
	}
	return false
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type Channel struct {
	Id                   int64    `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{2}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseReg struct {
	Rs                   bool     `protobuf:"varint,1,opt,name=rs,proto3" json:"rs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseReg) Reset()         { *m = ResponseReg{} }
func (m *ResponseReg) String() string { return proto.CompactTextString(m) }
func (*ResponseReg) ProtoMessage()    {}
func (*ResponseReg) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{3}
}

func (m *ResponseReg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseReg.Unmarshal(m, b)
}
func (m *ResponseReg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseReg.Marshal(b, m, deterministic)
}
func (m *ResponseReg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseReg.Merge(m, src)
}
func (m *ResponseReg) XXX_Size() int {
	return xxx_messageInfo_ResponseReg.Size(m)
}
func (m *ResponseReg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseReg.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseReg proto.InternalMessageInfo

func (m *ResponseReg) GetRs() bool {
	if m != nil {
		return m.Rs
	}
	return false
}

type MyHeader struct {
	Common               *Common  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyHeader) Reset()         { *m = MyHeader{} }
func (m *MyHeader) String() string { return proto.CompactTextString(m) }
func (*MyHeader) ProtoMessage()    {}
func (*MyHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{4}
}

func (m *MyHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyHeader.Unmarshal(m, b)
}
func (m *MyHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyHeader.Marshal(b, m, deterministic)
}
func (m *MyHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyHeader.Merge(m, src)
}
func (m *MyHeader) XXX_Size() int {
	return xxx_messageInfo_MyHeader.Size(m)
}
func (m *MyHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MyHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MyHeader proto.InternalMessageInfo

func (m *MyHeader) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*RequestRegPlayer)(nil), "pb.RequestRegPlayer")
	proto.RegisterMapType((map[uint64]*Channel)(nil), "pb.RequestRegPlayer.ChannelMapEntry")
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*Channel)(nil), "pb.Channel")
	proto.RegisterType((*ResponseReg)(nil), "pb.ResponseReg")
	proto.RegisterType((*MyHeader)(nil), "pb.MyHeader")
}

func init() { proto.RegisterFile("proto/demo.proto", fileDescriptor_bf10b39337e838aa) }

var fileDescriptor_bf10b39337e838aa = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xed, 0x3a, 0xb1, 0xe3, 0x4c, 0xbe, 0xaf, 0x35, 0xab, 0x0a, 0x99, 0x20, 0x24, 0x63, 0x71,
	0xb0, 0x28, 0xb8, 0xa8, 0xbd, 0x20, 0xb8, 0x51, 0x15, 0x15, 0x44, 0x11, 0x5a, 0x7a, 0xe2, 0x12,
	0x6d, 0xe2, 0x69, 0xb3, 0xaa, 0xbd, 0xbb, 0x78, 0x9d, 0x82, 0xff, 0x0a, 0xff, 0x8b, 0xff, 0x83,
	0x76, 0xd7, 0x44, 0x55, 0xd5, 0x03, 0xb7, 0x37, 0xef, 0xcd, 0x9b, 0xcc, 0x9b, 0xac, 0x21, 0xd1,
	0xad, 0xea, 0xd4, 0x61, 0x85, 0x8d, 0x2a, 0x1d, 0xa4, 0x81, 0x5e, 0xce, 0xa9, 0x67, 0x57, 0xaa,
	0x69, 0x94, 0xf4, 0x7c, 0xfe, 0x2b, 0x80, 0x84, 0xe1, 0xf7, 0x0d, 0x9a, 0x8e, 0xe1, 0xd5, 0x97,
	0x9a, 0xf7, 0xd8, 0xd2, 0x47, 0x10, 0xf3, 0xaa, 0x5a, 0x74, 0xa2, 0xc1, 0x94, 0x64, 0xa4, 0x08,
	0xd9, 0x84, 0x57, 0xd5, 0x85, 0x68, 0x90, 0x1e, 0xc0, 0x4c, 0xbb, 0xa6, 0x45, 0x2d, 0x4c, 0x97,
	0x8e, 0xb2, 0x51, 0x31, 0x3b, 0x82, 0x52, 0x2f, 0x4b, 0xef, 0x65, 0xe0, 0xe5, 0x4f, 0xc2, 0x74,
	0xb7, 0x9a, 0x85, 0xbc, 0x54, 0xe9, 0x38, 0x23, 0xf7, 0x37, 0x7f, 0x90, 0x97, 0x8a, 0x9e, 0xc2,
	0x6c, 0xb5, 0xe6, 0x52, 0x62, 0xbd, 0x68, 0xb8, 0x4e, 0x43, 0x37, 0xf9, 0x99, 0x6d, 0xbe, 0xbb,
	0x5f, 0x79, 0xe2, 0xfb, 0xce, 0xb9, 0x3e, 0x95, 0x5d, 0xdb, 0x33, 0x58, 0x6d, 0x89, 0xf9, 0x47,
	0xd8, 0xbb, 0x23, 0xd3, 0x04, 0x46, 0xd7, 0xd8, 0xbb, 0x24, 0x11, 0xb3, 0x90, 0x3e, 0x85, 0xf0,
	0x86, 0xd7, 0x1b, 0x4c, 0x03, 0xb7, 0xd2, 0xcc, 0xfe, 0xca, 0xe0, 0x62, 0x5e, 0x79, 0x13, 0xbc,
	0x26, 0xf9, 0x6f, 0x02, 0xd1, 0x70, 0x92, 0x5d, 0x08, 0x44, 0xe5, 0x46, 0x8c, 0x59, 0x20, 0x2a,
	0xfa, 0x18, 0xa6, 0xad, 0xaa, 0x71, 0x21, 0x79, 0xe3, 0xa7, 0xfc, 0xc7, 0x62, 0x4b, 0x7c, 0xe6,
	0x0d, 0xd2, 0x39, 0xc4, 0x52, 0xac, 0xae, 0x9d, 0x36, 0xca, 0x48, 0x31, 0x65, 0xdb, 0x9a, 0x3e,
	0x84, 0xc8, 0x74, 0xbc, 0xdb, 0x18, 0x77, 0x8e, 0x09, 0x1b, 0x2a, 0xba, 0x0f, 0xa1, 0x59, 0xa9,
	0x16, 0xd3, 0x30, 0x23, 0x45, 0xc0, 0x7c, 0x41, 0x5f, 0x00, 0xe8, 0xb5, 0x92, 0xb8, 0xe8, 0x7a,
	0x8d, 0x69, 0x94, 0x91, 0x62, 0xf7, 0xe8, 0x7f, 0x77, 0x40, 0xcb, 0x5e, 0xf4, 0x1a, 0xd9, 0x54,
	0xff, 0x85, 0x36, 0xa8, 0xc1, 0x9f, 0xe9, 0x24, 0x23, 0x45, 0xcc, 0x2c, 0xb4, 0x53, 0x6b, 0xbc,
	0xc1, 0x3a, 0x8d, 0x33, 0x52, 0x3c, 0x60, 0xbe, 0xc8, 0x5f, 0xc2, 0x64, 0x48, 0x7b, 0x2b, 0x17,
	0x75, 0xb9, 0x28, 0x8c, 0xb7, 0x91, 0xa6, 0xcc, 0xe1, 0xfc, 0x09, 0xcc, 0x18, 0x1a, 0xad, 0xa4,
	0x41, 0x86, 0x57, 0xd6, 0xd2, 0x1a, 0x67, 0x89, 0x59, 0xd0, 0x9a, 0xbc, 0x84, 0xf8, 0xbc, 0x3f,
	0x43, 0x5e, 0x61, 0x4b, 0x73, 0x88, 0xfc, 0xf3, 0x72, 0xfa, 0xf0, 0x67, 0x9f, 0x38, 0x86, 0x0d,
	0xca, 0xf3, 0x03, 0x98, 0x6e, 0xb7, 0xa7, 0x00, 0x51, 0xa3, 0x96, 0xa2, 0xc6, 0x64, 0x87, 0xc6,
	0x30, 0x5e, 0xab, 0x06, 0x13, 0x62, 0xd1, 0x0f, 0xd5, 0x56, 0x49, 0x70, 0x24, 0x21, 0x7c, 0x2f,
	0x5a, 0xd3, 0xd1, 0x63, 0x88, 0xbf, 0xf2, 0xfe, 0x0c, 0xeb, 0x5a, 0xd1, 0xfd, 0xfb, 0x5e, 0xc5,
	0x7c, 0xcf, 0xb3, 0xdb, 0x45, 0xf3, 0x1d, 0xfa, 0x0a, 0x42, 0x6b, 0x12, 0xff, 0xec, 0x78, 0x37,
	0xf9, 0x16, 0x96, 0x87, 0x6f, 0xf5, 0x72, 0x19, 0xb9, 0xef, 0xe3, 0xf8, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd7, 0x25, 0x38, 0x5b, 0x4b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FirstClient is the client API for First service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirstClient interface {
	SayHello(ctx context.Context, in *RequestRegPlayer, opts ...grpc.CallOption) (*ResponseReg, error)
	SayHi(ctx context.Context, in *RequestRegPlayer, opts ...grpc.CallOption) (*ResponseReg, error)
}

type firstClient struct {
	cc *grpc.ClientConn
}

func NewFirstClient(cc *grpc.ClientConn) FirstClient {
	return &firstClient{cc}
}

func (c *firstClient) SayHello(ctx context.Context, in *RequestRegPlayer, opts ...grpc.CallOption) (*ResponseReg, error) {
	out := new(ResponseReg)
	err := c.cc.Invoke(ctx, "/pb.First/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firstClient) SayHi(ctx context.Context, in *RequestRegPlayer, opts ...grpc.CallOption) (*ResponseReg, error) {
	out := new(ResponseReg)
	err := c.cc.Invoke(ctx, "/pb.First/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstServer is the server API for First service.
type FirstServer interface {
	SayHello(context.Context, *RequestRegPlayer) (*ResponseReg, error)
	SayHi(context.Context, *RequestRegPlayer) (*ResponseReg, error)
}

// UnimplementedFirstServer can be embedded to have forward compatible implementations.
type UnimplementedFirstServer struct {
}

func (*UnimplementedFirstServer) SayHello(ctx context.Context, req *RequestRegPlayer) (*ResponseReg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedFirstServer) SayHi(ctx context.Context, req *RequestRegPlayer) (*ResponseReg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}

func RegisterFirstServer(s *grpc.Server, srv FirstServer) {
	s.RegisterService(&_First_serviceDesc, srv)
}

func _First_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRegPlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.First/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServer).SayHello(ctx, req.(*RequestRegPlayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _First_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRegPlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.First/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServer).SayHi(ctx, req.(*RequestRegPlayer))
	}
	return interceptor(ctx, in, info, handler)
}

var _First_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.First",
	HandlerType: (*FirstServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _First_SayHello_Handler,
		},
		{
			MethodName: "SayHi",
			Handler:    _First_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}
