// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twin_agora.proto

package pb // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 房间心跳
type RoomHeartbeatReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid                  int32    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomHeartbeatReq) Reset()         { *m = RoomHeartbeatReq{} }
func (m *RoomHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*RoomHeartbeatReq) ProtoMessage()    {}
func (*RoomHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{0}
}
func (m *RoomHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomHeartbeatReq.Unmarshal(m, b)
}
func (m *RoomHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomHeartbeatReq.Marshal(b, m, deterministic)
}
func (dst *RoomHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomHeartbeatReq.Merge(dst, src)
}
func (m *RoomHeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_RoomHeartbeatReq.Size(m)
}
func (m *RoomHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomHeartbeatReq proto.InternalMessageInfo

func (m *RoomHeartbeatReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *RoomHeartbeatReq) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RoomHeartbeatReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomHeartbeatReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// 呼叫某人，加入一个房间，进行：音视频通话
type CancelCallPeopleReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelCallPeopleReq) Reset()         { *m = CancelCallPeopleReq{} }
func (m *CancelCallPeopleReq) String() string { return proto.CompactTextString(m) }
func (*CancelCallPeopleReq) ProtoMessage()    {}
func (*CancelCallPeopleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{1}
}
func (m *CancelCallPeopleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCallPeopleReq.Unmarshal(m, b)
}
func (m *CancelCallPeopleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCallPeopleReq.Marshal(b, m, deterministic)
}
func (dst *CancelCallPeopleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCallPeopleReq.Merge(dst, src)
}
func (m *CancelCallPeopleReq) XXX_Size() int {
	return xxx_messageInfo_CancelCallPeopleReq.Size(m)
}
func (m *CancelCallPeopleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCallPeopleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCallPeopleReq proto.InternalMessageInfo

func (m *CancelCallPeopleReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CancelCallPeopleReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CancelCallPeopleReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// 专家发出应答选择
type CallVote struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallVote) Reset()         { *m = CallVote{} }
func (m *CallVote) String() string { return proto.CompactTextString(m) }
func (*CallVote) ProtoMessage()    {}
func (*CallVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{2}
}
func (m *CallVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallVote.Unmarshal(m, b)
}
func (m *CallVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallVote.Marshal(b, m, deterministic)
}
func (dst *CallVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallVote.Merge(dst, src)
}
func (m *CallVote) XXX_Size() int {
	return xxx_messageInfo_CallVote.Size(m)
}
func (m *CallVote) XXX_DiscardUnknown() {
	xxx_messageInfo_CallVote.DiscardUnknown(m)
}

var xxx_messageInfo_CallVote proto.InternalMessageInfo

func (m *CallVote) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallVote) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallVote) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// 呼叫某人，加入一个房间，进行：音视频通话
type CallPeopleReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	PeopleType           int32    `protobuf:"varint,5,opt,name=people_type,json=peopleType,proto3" json:"people_type,omitempty"`
	PeopleRole           int32    `protobuf:"varint,6,opt,name=people_role,json=peopleRole,proto3" json:"people_role,omitempty"`
	AgoraAppId           string   `protobuf:"bytes,7,opt,name=agora_app_id,json=agoraAppId,proto3" json:"agora_app_id,omitempty"`
	AgoraChannel         string   `protobuf:"bytes,8,opt,name=agora_channel,json=agoraChannel,proto3" json:"agora_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleReq) Reset()         { *m = CallPeopleReq{} }
func (m *CallPeopleReq) String() string { return proto.CompactTextString(m) }
func (*CallPeopleReq) ProtoMessage()    {}
func (*CallPeopleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{3}
}
func (m *CallPeopleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleReq.Unmarshal(m, b)
}
func (m *CallPeopleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleReq.Marshal(b, m, deterministic)
}
func (dst *CallPeopleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleReq.Merge(dst, src)
}
func (m *CallPeopleReq) XXX_Size() int {
	return xxx_messageInfo_CallPeopleReq.Size(m)
}
func (m *CallPeopleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleReq proto.InternalMessageInfo

func (m *CallPeopleReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallPeopleReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallPeopleReq) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *CallPeopleReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleReq) GetPeopleType() int32 {
	if m != nil {
		return m.PeopleType
	}
	return 0
}

func (m *CallPeopleReq) GetPeopleRole() int32 {
	if m != nil {
		return m.PeopleRole
	}
	return 0
}

func (m *CallPeopleReq) GetAgoraAppId() string {
	if m != nil {
		return m.AgoraAppId
	}
	return ""
}

func (m *CallPeopleReq) GetAgoraChannel() string {
	if m != nil {
		return m.AgoraChannel
	}
	return ""
}

// 给发发起呼叫者，做出应答
type CallPeopleRes struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	ReceiveUid           string   `protobuf:"bytes,2,opt,name=receive_uid,json=receiveUid,proto3" json:"receive_uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	ErrCode              int32    `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	RoomId               string   `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AgoraAppId           string   `protobuf:"bytes,7,opt,name=agora_app_id,json=agoraAppId,proto3" json:"agora_app_id,omitempty"`
	AgoraChannel         string   `protobuf:"bytes,8,opt,name=agora_channel,json=agoraChannel,proto3" json:"agora_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleRes) Reset()         { *m = CallPeopleRes{} }
func (m *CallPeopleRes) String() string { return proto.CompactTextString(m) }
func (*CallPeopleRes) ProtoMessage()    {}
func (*CallPeopleRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{4}
}
func (m *CallPeopleRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleRes.Unmarshal(m, b)
}
func (m *CallPeopleRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleRes.Marshal(b, m, deterministic)
}
func (dst *CallPeopleRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleRes.Merge(dst, src)
}
func (m *CallPeopleRes) XXX_Size() int {
	return xxx_messageInfo_CallPeopleRes.Size(m)
}
func (m *CallPeopleRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleRes.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleRes proto.InternalMessageInfo

func (m *CallPeopleRes) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallPeopleRes) GetReceiveUid() string {
	if m != nil {
		return m.ReceiveUid
	}
	return ""
}

func (m *CallPeopleRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleRes) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CallPeopleRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CallPeopleRes) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *CallPeopleRes) GetAgoraAppId() string {
	if m != nil {
		return m.AgoraAppId
	}
	return ""
}

func (m *CallPeopleRes) GetAgoraChannel() string {
	if m != nil {
		return m.AgoraChannel
	}
	return ""
}

// 某人进入了一个房间/频道，通知给C端
type PeopleEntry struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	RoomId               string   `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleEntry) Reset()         { *m = PeopleEntry{} }
func (m *PeopleEntry) String() string { return proto.CompactTextString(m) }
func (*PeopleEntry) ProtoMessage()    {}
func (*PeopleEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{5}
}
func (m *PeopleEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleEntry.Unmarshal(m, b)
}
func (m *PeopleEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleEntry.Marshal(b, m, deterministic)
}
func (dst *PeopleEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleEntry.Merge(dst, src)
}
func (m *PeopleEntry) XXX_Size() int {
	return xxx_messageInfo_PeopleEntry.Size(m)
}
func (m *PeopleEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleEntry proto.InternalMessageInfo

func (m *PeopleEntry) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *PeopleEntry) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PeopleEntry) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PeopleEntry) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// 某人进入了一个房间/频道，通知给C端
type PeopleLeaveRes struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	RoomId               string   `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleLeaveRes) Reset()         { *m = PeopleLeaveRes{} }
func (m *PeopleLeaveRes) String() string { return proto.CompactTextString(m) }
func (*PeopleLeaveRes) ProtoMessage()    {}
func (*PeopleLeaveRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{6}
}
func (m *PeopleLeaveRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleLeaveRes.Unmarshal(m, b)
}
func (m *PeopleLeaveRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleLeaveRes.Marshal(b, m, deterministic)
}
func (dst *PeopleLeaveRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleLeaveRes.Merge(dst, src)
}
func (m *PeopleLeaveRes) XXX_Size() int {
	return xxx_messageInfo_PeopleLeaveRes.Size(m)
}
func (m *PeopleLeaveRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleLeaveRes.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleLeaveRes proto.InternalMessageInfo

func (m *PeopleLeaveRes) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *PeopleLeaveRes) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PeopleLeaveRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PeopleLeaveRes) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// 给某人推送一条消息
type CallReply struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	SendUid              int32    `protobuf:"varint,2,opt,name=send_uid,json=sendUid,proto3" json:"send_uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MsgType              int32    `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	RoomId               string   `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallReply) Reset()         { *m = CallReply{} }
func (m *CallReply) String() string { return proto.CompactTextString(m) }
func (*CallReply) ProtoMessage()    {}
func (*CallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_twin_agora_8e78767d5980a8bb, []int{7}
}
func (m *CallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallReply.Unmarshal(m, b)
}
func (m *CallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallReply.Marshal(b, m, deterministic)
}
func (dst *CallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallReply.Merge(dst, src)
}
func (m *CallReply) XXX_Size() int {
	return xxx_messageInfo_CallReply.Size(m)
}
func (m *CallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CallReply.DiscardUnknown(m)
}

var xxx_messageInfo_CallReply proto.InternalMessageInfo

func (m *CallReply) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallReply) GetSendUid() int32 {
	if m != nil {
		return m.SendUid
	}
	return 0
}

func (m *CallReply) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *CallReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CallReply) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *CallReply) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomHeartbeatReq)(nil), "pb.RoomHeartbeatReq")
	proto.RegisterType((*CancelCallPeopleReq)(nil), "pb.CancelCallPeopleReq")
	proto.RegisterType((*CallVote)(nil), "pb.CallVote")
	proto.RegisterType((*CallPeopleReq)(nil), "pb.CallPeopleReq")
	proto.RegisterType((*CallPeopleRes)(nil), "pb.CallPeopleRes")
	proto.RegisterType((*PeopleEntry)(nil), "pb.PeopleEntry")
	proto.RegisterType((*PeopleLeaveRes)(nil), "pb.PeopleLeaveRes")
	proto.RegisterType((*CallReply)(nil), "pb.CallReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwinAgoraClient is the client API for TwinAgora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwinAgoraClient interface {
	CS_Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Empty, error)
	CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	CS_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	CS_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error)
	CS_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error)
	CS_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	CS_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	CS_RoomHeartbeat(ctx context.Context, in *RoomHeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeople(ctx context.Context, in *CallPeopleRes, opts ...grpc.CallOption) (*Empty, error)
	SC_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	SC_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error)
	SC_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error)
	SC_CallReply(ctx context.Context, in *CallReply, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	FdClose(ctx context.Context, in *FDCloseEvent, opts ...grpc.CallOption) (*Empty, error)
	FdCreate(ctx context.Context, in *FDCreateEvent, opts ...grpc.CallOption) (*Empty, error)
}

type twinAgoraClient struct {
	cc *grpc.ClientConn
}

func NewTwinAgoraClient(cc *grpc.ClientConn) TwinAgoraClient {
	return &twinAgoraClient{cc}
}

func (c *twinAgoraClient) CS_Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CancelCallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_PeopleEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_PeopleLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeopleAccept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeopleDeny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_RoomHeartbeat(ctx context.Context, in *RoomHeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_RoomHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeople(ctx context.Context, in *CallPeopleRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CancelCallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PeopleEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PeopleLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallReply(ctx context.Context, in *CallReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeopleAccept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeopleDeny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) FdClose(ctx context.Context, in *FDCloseEvent, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/FdClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) FdCreate(ctx context.Context, in *FDCreateEvent, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/FdCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinAgoraServer is the server API for TwinAgora service.
type TwinAgoraServer interface {
	CS_Heartbeat(context.Context, *Heartbeat) (*Empty, error)
	CS_CallPeople(context.Context, *CallPeopleReq) (*Empty, error)
	CS_CancelCallPeople(context.Context, *CancelCallPeopleReq) (*Empty, error)
	CS_PeopleEntry(context.Context, *PeopleEntry) (*Empty, error)
	CS_PeopleLeave(context.Context, *PeopleLeaveRes) (*Empty, error)
	CS_CallPeopleAccept(context.Context, *CallVote) (*Empty, error)
	CS_CallPeopleDeny(context.Context, *CallVote) (*Empty, error)
	CS_RoomHeartbeat(context.Context, *RoomHeartbeatReq) (*Empty, error)
	SC_CallPeople(context.Context, *CallPeopleRes) (*Empty, error)
	SC_CancelCallPeople(context.Context, *CancelCallPeopleReq) (*Empty, error)
	SC_PeopleEntry(context.Context, *PeopleEntry) (*Empty, error)
	SC_PeopleLeave(context.Context, *PeopleLeaveRes) (*Empty, error)
	SC_CallReply(context.Context, *CallReply) (*Empty, error)
	SC_CallPeopleAccept(context.Context, *CallVote) (*Empty, error)
	SC_CallPeopleDeny(context.Context, *CallVote) (*Empty, error)
	FdClose(context.Context, *FDCloseEvent) (*Empty, error)
	FdCreate(context.Context, *FDCreateEvent) (*Empty, error)
}

func RegisterTwinAgoraServer(s *grpc.Server, srv TwinAgoraServer) {
	s.RegisterService(&_TwinAgora_serviceDesc, srv)
}

func _TwinAgora_CS_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_Heartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, req.(*CallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CancelCallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CancelCallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CancelCallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CancelCallPeople(ctx, req.(*CancelCallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_PeopleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_PeopleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_PeopleEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_PeopleEntry(ctx, req.(*PeopleEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_PeopleLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleLeaveRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_PeopleLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_PeopleLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_PeopleLeave(ctx, req.(*PeopleLeaveRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CallPeopleAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeopleAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeopleAccept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeopleAccept(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CallPeopleDeny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeopleDeny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeopleDeny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeopleDeny(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_RoomHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_RoomHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_RoomHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_RoomHeartbeat(ctx, req.(*RoomHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPeopleRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeople(ctx, req.(*CallPeopleRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CancelCallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CancelCallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CancelCallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CancelCallPeople(ctx, req.(*CancelCallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PeopleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PeopleEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, req.(*PeopleEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PeopleLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleLeaveRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PeopleLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PeopleLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PeopleLeave(ctx, req.(*PeopleLeaveRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallReply(ctx, req.(*CallReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeopleAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeopleAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeopleAccept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeopleAccept(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeopleDeny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeopleDeny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeopleDeny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeopleDeny(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_FdClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FDCloseEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).FdClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/FdClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).FdClose(ctx, req.(*FDCloseEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_FdCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FDCreateEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).FdCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/FdCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).FdCreate(ctx, req.(*FDCreateEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwinAgora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TwinAgora",
	HandlerType: (*TwinAgoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CS_Heartbeat",
			Handler:    _TwinAgora_CS_Heartbeat_Handler,
		},
		{
			MethodName: "CS_CallPeople",
			Handler:    _TwinAgora_CS_CallPeople_Handler,
		},
		{
			MethodName: "CS_CancelCallPeople",
			Handler:    _TwinAgora_CS_CancelCallPeople_Handler,
		},
		{
			MethodName: "CS_PeopleEntry",
			Handler:    _TwinAgora_CS_PeopleEntry_Handler,
		},
		{
			MethodName: "CS_PeopleLeave",
			Handler:    _TwinAgora_CS_PeopleLeave_Handler,
		},
		{
			MethodName: "CS_CallPeopleAccept",
			Handler:    _TwinAgora_CS_CallPeopleAccept_Handler,
		},
		{
			MethodName: "CS_CallPeopleDeny",
			Handler:    _TwinAgora_CS_CallPeopleDeny_Handler,
		},
		{
			MethodName: "CS_RoomHeartbeat",
			Handler:    _TwinAgora_CS_RoomHeartbeat_Handler,
		},
		{
			MethodName: "SC_CallPeople",
			Handler:    _TwinAgora_SC_CallPeople_Handler,
		},
		{
			MethodName: "SC_CancelCallPeople",
			Handler:    _TwinAgora_SC_CancelCallPeople_Handler,
		},
		{
			MethodName: "SC_PeopleEntry",
			Handler:    _TwinAgora_SC_PeopleEntry_Handler,
		},
		{
			MethodName: "SC_PeopleLeave",
			Handler:    _TwinAgora_SC_PeopleLeave_Handler,
		},
		{
			MethodName: "SC_CallReply",
			Handler:    _TwinAgora_SC_CallReply_Handler,
		},
		{
			MethodName: "SC_CallPeopleAccept",
			Handler:    _TwinAgora_SC_CallPeopleAccept_Handler,
		},
		{
			MethodName: "SC_CallPeopleDeny",
			Handler:    _TwinAgora_SC_CallPeopleDeny_Handler,
		},
		{
			MethodName: "FdClose",
			Handler:    _TwinAgora_FdClose_Handler,
		},
		{
			MethodName: "FdCreate",
			Handler:    _TwinAgora_FdCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twin_agora.proto",
}

func init() { proto.RegisterFile("twin_agora.proto", fileDescriptor_twin_agora_8e78767d5980a8bb) }

var fileDescriptor_twin_agora_8e78767d5980a8bb = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x6e, 0x12, 0x88, 0xe3, 0x21, 0xa1, 0x61, 0xa9, 0x44, 0x40, 0x42, 0x44, 0xe9, 0x25, 0xe2,
	0x10, 0xfa, 0xa3, 0x9e, 0x38, 0x51, 0x43, 0x54, 0xa4, 0x56, 0xaa, 0x1c, 0xe8, 0xa1, 0x17, 0xcb,
	0xb1, 0x47, 0xa9, 0x25, 0x7b, 0x77, 0x59, 0x2f, 0xa0, 0x5c, 0xfb, 0x48, 0x7d, 0x98, 0xbe, 0x4d,
	0xa5, 0x6a, 0x77, 0xe3, 0xe0, 0x4d, 0x04, 0x84, 0x96, 0x9b, 0x67, 0x76, 0xbe, 0xf9, 0xf9, 0xe6,
	0xf3, 0xda, 0xd0, 0x96, 0xb7, 0x09, 0x0d, 0xc2, 0x09, 0x13, 0xe1, 0x80, 0x0b, 0x26, 0x19, 0xa9,
	0xf2, 0xf1, 0x5e, 0x33, 0x62, 0x59, 0xc6, 0xa8, 0xf1, 0xf4, 0x38, 0xb4, 0x7d, 0xc6, 0xb2, 0x4f,
	0x18, 0x0a, 0x39, 0xc6, 0x50, 0xfa, 0x78, 0x45, 0xf6, 0x01, 0x72, 0x76, 0x2d, 0x22, 0x0c, 0xae,
	0x93, 0xb8, 0x53, 0xe9, 0x56, 0xfa, 0xeb, 0xbe, 0x6b, 0x3c, 0x97, 0x49, 0x4c, 0x08, 0xac, 0xc9,
	0x24, 0xc3, 0x4e, 0xb5, 0x5b, 0xe9, 0xd7, 0x7c, 0xfd, 0x4c, 0x76, 0xc0, 0x11, 0x8c, 0x65, 0x41,
	0x12, 0x77, 0x6a, 0xdd, 0x4a, 0xdf, 0xf5, 0xeb, 0xca, 0x3c, 0x8f, 0x49, 0x1b, 0x6a, 0x2a, 0xc9,
	0x9a, 0x4e, 0xa2, 0x1e, 0x7b, 0x01, 0x6c, 0x7b, 0x21, 0x8d, 0x30, 0xf5, 0xc2, 0x34, 0xfd, 0x8a,
	0x8c, 0xa7, 0xb8, 0x42, 0xd1, 0x59, 0x9e, 0xea, 0x3c, 0xcf, 0xbd, 0x25, 0x7b, 0x17, 0xd0, 0x50,
	0xa9, 0xbf, 0x31, 0x89, 0xcf, 0x98, 0xf5, 0x67, 0x15, 0x5a, 0xff, 0xd9, 0xf1, 0x3e, 0x80, 0x0c,
	0xc5, 0x04, 0xa5, 0x06, 0xd4, 0x0c, 0xc0, 0x78, 0x14, 0xa0, 0x03, 0x4e, 0xf4, 0x23, 0xa4, 0x14,
	0x53, 0x4d, 0x97, 0xeb, 0x17, 0x26, 0x39, 0x80, 0x0d, 0xae, 0xcb, 0x06, 0x72, 0xca, 0xb1, 0xb3,
	0xae, 0x91, 0x60, 0x5c, 0x17, 0x53, 0x8e, 0xa5, 0x00, 0xc1, 0x52, 0xec, 0xd4, 0xcb, 0x01, 0x3e,
	0x4b, 0x91, 0x74, 0xa1, 0xa9, 0x75, 0x10, 0x84, 0x9c, 0xab, 0xd9, 0x1c, 0x5d, 0x00, 0xb4, 0xef,
	0x84, 0xf3, 0xf3, 0x98, 0xbc, 0x86, 0x96, 0x89, 0x28, 0x7a, 0x68, 0xe8, 0x10, 0x03, 0xf3, 0x8c,
	0xaf, 0xf7, 0xa7, 0x62, 0x93, 0x90, 0x3f, 0x46, 0xc2, 0x01, 0x6c, 0x08, 0x8c, 0x30, 0xb9, 0x31,
	0xe7, 0x55, 0x53, 0x76, 0xe6, 0x5a, 0x18, 0xba, 0x66, 0x0f, 0xbd, 0x0b, 0x0d, 0x14, 0x22, 0x88,
	0x58, 0x8c, 0x33, 0xf9, 0x38, 0x28, 0x84, 0xc7, 0x62, 0xad, 0x36, 0x75, 0x94, 0xe5, 0x13, 0xcd,
	0x85, 0xeb, 0xd7, 0x51, 0x88, 0x2f, 0xf9, 0xa4, 0xbc, 0xbd, 0xba, 0x25, 0xc3, 0x67, 0x9a, 0xff,
	0x0a, 0x36, 0xcc, 0xe8, 0x67, 0x54, 0x8a, 0xe9, 0xd3, 0x15, 0x70, 0xff, 0xb4, 0xa5, 0xce, 0xd7,
	0x2c, 0xdd, 0x49, 0xd8, 0x34, 0x25, 0x3f, 0x63, 0x78, 0xb3, 0x0a, 0xe5, 0xcf, 0x52, 0xf5, 0x57,
	0x05, 0x5c, 0xb5, 0x68, 0x1f, 0x79, 0xfa, 0xe8, 0x9c, 0xbb, 0xd0, 0xc8, 0x91, 0xc6, 0xc1, 0x5d,
	0x59, 0x47, 0xd9, 0x97, 0xab, 0x49, 0x9e, 0x51, 0x89, 0x54, 0xce, 0x25, 0x6f, 0x4c, 0x95, 0x33,
	0xcb, 0x27, 0x65, 0xbd, 0x3b, 0x59, 0x3e, 0xd1, 0x62, 0xbf, 0x6f, 0xc9, 0xef, 0x7e, 0xd7, 0xc1,
	0xbd, 0xb8, 0x4d, 0xe8, 0x89, 0x5a, 0x19, 0x39, 0x84, 0xa6, 0x37, 0x0a, 0xe6, 0x17, 0x1b, 0x69,
	0x0d, 0xf8, 0x78, 0x30, 0x37, 0xf7, 0x5c, 0x65, 0x9e, 0x65, 0x5c, 0x4e, 0x7b, 0x2f, 0xc8, 0x11,
	0xb4, 0xbc, 0x51, 0x70, 0xa7, 0x6c, 0xb2, 0xa5, 0x4e, 0xad, 0xd7, 0xdd, 0x06, 0x1c, 0xc3, 0xb6,
	0x06, 0xd8, 0xf7, 0x18, 0xd9, 0x31, 0xb0, 0xa5, 0xdb, 0xcd, 0x06, 0x0f, 0x60, 0xd3, 0x1b, 0x05,
	0x65, 0x21, 0xbd, 0x54, 0xc7, 0x25, 0x87, 0x1d, 0xff, 0xb6, 0x14, 0xaf, 0x55, 0x40, 0xc8, 0x5d,
	0x7c, 0x21, 0x0b, 0x1b, 0xf2, 0x66, 0xd6, 0x5f, 0xd1, 0xc3, 0x49, 0x14, 0x21, 0x97, 0xa4, 0x59,
	0x8c, 0xa5, 0x2e, 0xc7, 0xc5, 0xa6, 0xb6, 0x2c, 0xc4, 0x29, 0xd2, 0xe9, 0x43, 0xf1, 0x1f, 0xa0,
	0xed, 0x8d, 0x02, 0xeb, 0xdb, 0x41, 0x5e, 0xa9, 0x80, 0xc5, 0xcf, 0xc9, 0x12, 0xd3, 0x23, 0xef,
	0x41, 0xa6, 0xf3, 0x25, 0xa6, 0x35, 0xe0, 0x5f, 0x99, 0x1e, 0x79, 0x4f, 0x63, 0x7a, 0x1e, 0xbf,
	0x22, 0xd3, 0x87, 0xd0, 0x9c, 0x0d, 0x64, 0xde, 0x95, 0x56, 0x31, 0x8f, 0x36, 0x97, 0xb6, 0x62,
	0x0d, 0xbf, 0xd2, 0x56, 0x2c, 0xc4, 0x63, 0x5b, 0xe9, 0x83, 0x33, 0x8c, 0xbd, 0x94, 0xe5, 0x48,
	0xda, 0xca, 0x3f, 0x3c, 0xd5, 0xc6, 0xd9, 0x0d, 0x52, 0xb9, 0xd8, 0x77, 0x63, 0x18, 0x7b, 0x02,
	0x43, 0x39, 0xdb, 0xc1, 0xf0, 0xd4, 0x58, 0xcb, 0xb1, 0x1f, 0x9d, 0xef, 0xeb, 0x83, 0xa3, 0x63,
	0x3e, 0x1e, 0xd7, 0xf5, 0x4f, 0xc3, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x12, 0x28, 0xe4,
	0x8c, 0x5a, 0x08, 0x00, 0x00,
}
