// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twin_agora.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//呼叫某人，加入一个房间，进行：音视频通话
type CallPeopleReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PeopleType           int32    `protobuf:"varint,4,opt,name=people_type,json=peopleType,proto3" json:"people_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleReq) Reset()         { *m = CallPeopleReq{} }
func (m *CallPeopleReq) String() string { return proto.CompactTextString(m) }
func (*CallPeopleReq) ProtoMessage()    {}
func (*CallPeopleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{0}
}

func (m *CallPeopleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleReq.Unmarshal(m, b)
}
func (m *CallPeopleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleReq.Marshal(b, m, deterministic)
}
func (m *CallPeopleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleReq.Merge(m, src)
}
func (m *CallPeopleReq) XXX_Size() int {
	return xxx_messageInfo_CallPeopleReq.Size(m)
}
func (m *CallPeopleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleReq proto.InternalMessageInfo

func (m *CallPeopleReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallPeopleReq) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *CallPeopleReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleReq) GetPeopleType() int32 {
	if m != nil {
		return m.PeopleType
	}
	return 0
}

type CallPeopleRes struct {
	ReceiveUid           string   `protobuf:"bytes,1,opt,name=receive_uid,json=receiveUid,proto3" json:"receive_uid,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	ErrCode              int32    `protobuf:"varint,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleRes) Reset()         { *m = CallPeopleRes{} }
func (m *CallPeopleRes) String() string { return proto.CompactTextString(m) }
func (*CallPeopleRes) ProtoMessage()    {}
func (*CallPeopleRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{1}
}

func (m *CallPeopleRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleRes.Unmarshal(m, b)
}
func (m *CallPeopleRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleRes.Marshal(b, m, deterministic)
}
func (m *CallPeopleRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleRes.Merge(m, src)
}
func (m *CallPeopleRes) XXX_Size() int {
	return xxx_messageInfo_CallPeopleRes.Size(m)
}
func (m *CallPeopleRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleRes.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleRes proto.InternalMessageInfo

func (m *CallPeopleRes) GetReceiveUid() string {
	if m != nil {
		return m.ReceiveUid
	}
	return ""
}

func (m *CallPeopleRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleRes) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CallPeopleRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//某人进入了一个房间/频道，通知给C端
type PeopleEntryRes struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PeopleType           string   `protobuf:"bytes,4,opt,name=people_type,json=peopleType,proto3" json:"people_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleEntryRes) Reset()         { *m = PeopleEntryRes{} }
func (m *PeopleEntryRes) String() string { return proto.CompactTextString(m) }
func (*PeopleEntryRes) ProtoMessage()    {}
func (*PeopleEntryRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{2}
}

func (m *PeopleEntryRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleEntryRes.Unmarshal(m, b)
}
func (m *PeopleEntryRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleEntryRes.Marshal(b, m, deterministic)
}
func (m *PeopleEntryRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleEntryRes.Merge(m, src)
}
func (m *PeopleEntryRes) XXX_Size() int {
	return xxx_messageInfo_PeopleEntryRes.Size(m)
}
func (m *PeopleEntryRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleEntryRes.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleEntryRes proto.InternalMessageInfo

func (m *PeopleEntryRes) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PeopleEntryRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PeopleEntryRes) GetPeopleType() string {
	if m != nil {
		return m.PeopleType
	}
	return ""
}

//给某人推送一条消息
type PushMsgRes struct {
	SendUid              int32    `protobuf:"varint,1,opt,name=send_uid,json=sendUid,proto3" json:"send_uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgType              int32    `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgRes) Reset()         { *m = PushMsgRes{} }
func (m *PushMsgRes) String() string { return proto.CompactTextString(m) }
func (*PushMsgRes) ProtoMessage()    {}
func (*PushMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{3}
}

func (m *PushMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgRes.Unmarshal(m, b)
}
func (m *PushMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgRes.Marshal(b, m, deterministic)
}
func (m *PushMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgRes.Merge(m, src)
}
func (m *PushMsgRes) XXX_Size() int {
	return xxx_messageInfo_PushMsgRes.Size(m)
}
func (m *PushMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgRes proto.InternalMessageInfo

func (m *PushMsgRes) GetSendUid() int32 {
	if m != nil {
		return m.SendUid
	}
	return 0
}

func (m *PushMsgRes) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *PushMsgRes) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushMsgRes) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func init() {
	proto.RegisterType((*CallPeopleReq)(nil), "pb.CallPeopleReq")
	proto.RegisterType((*CallPeopleRes)(nil), "pb.CallPeopleRes")
	proto.RegisterType((*PeopleEntryRes)(nil), "pb.PeopleEntryRes")
	proto.RegisterType((*PushMsgRes)(nil), "pb.PushMsgRes")
}

func init() { proto.RegisterFile("twin_agora.proto", fileDescriptor_223ae5106ca5efe7) }

var fileDescriptor_223ae5106ca5efe7 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4b, 0x8f, 0xda, 0x30,
	0x10, 0x26, 0x50, 0x08, 0x99, 0x16, 0x44, 0x7d, 0x69, 0x40, 0xaa, 0x8a, 0x72, 0xa2, 0x97, 0x54,
	0x6d, 0x0f, 0x3d, 0xf4, 0xd4, 0x46, 0x1c, 0x91, 0x50, 0x80, 0x4b, 0xa5, 0xca, 0xca, 0x63, 0x14,
	0x22, 0x25, 0xb6, 0x6b, 0x9b, 0xa2, 0x08, 0xa9, 0x3f, 0xa6, 0xbf, 0x74, 0xe5, 0x64, 0x79, 0x64,
	0xb9, 0xec, 0xde, 0x3c, 0x9f, 0x67, 0xe6, 0x7b, 0xd8, 0x30, 0xd1, 0xc7, 0x9c, 0xd1, 0x28, 0xe3,
	0x32, 0xf2, 0x85, 0xe4, 0x9a, 0x93, 0xae, 0x88, 0x67, 0x6f, 0x12, 0x5e, 0x96, 0x9c, 0x35, 0x88,
	0x77, 0x82, 0x51, 0x10, 0x15, 0xc5, 0x1a, 0xb9, 0x28, 0x30, 0xc4, 0x3f, 0x64, 0x02, 0xbd, 0x43,
	0x9e, 0xba, 0xd6, 0xdc, 0x5a, 0xf4, 0x43, 0x73, 0x24, 0xef, 0x01, 0x74, 0x24, 0x33, 0xd4, 0xd4,
	0x5c, 0x74, 0xeb, 0x0b, 0xa7, 0x41, 0x76, 0x79, 0x4a, 0x5c, 0xb0, 0x93, 0x7d, 0xc4, 0x18, 0x16,
	0x6e, 0x6f, 0x6e, 0x2d, 0x9c, 0xf0, 0x5c, 0x92, 0x0f, 0xf0, 0x5a, 0xd4, 0x7b, 0xa9, 0xae, 0x04,
	0xba, 0xaf, 0xea, 0x49, 0x68, 0xa0, 0x6d, 0x25, 0xd0, 0xfb, 0xd7, 0x26, 0x57, 0x66, 0x42, 0x62,
	0x82, 0xf9, 0x5f, 0xa4, 0x67, 0x11, 0x4e, 0x08, 0x8f, 0xd0, 0x13, 0xb2, 0x6e, 0x9b, 0x6c, 0x0a,
	0x43, 0x94, 0x92, 0x26, 0x3c, 0xc5, 0x5a, 0x47, 0x3f, 0xb4, 0x51, 0xca, 0x80, 0xa7, 0x48, 0xde,
	0x81, 0x39, 0xd2, 0x52, 0x65, 0xb5, 0x06, 0x27, 0x1c, 0xa0, 0x94, 0x2b, 0x95, 0x79, 0xbf, 0x61,
	0xdc, 0x70, 0x2f, 0x99, 0x96, 0x95, 0x11, 0x70, 0xef, 0xfe, 0x45, 0xf6, 0x9c, 0x96, 0xbd, 0x13,
	0xc0, 0xfa, 0xa0, 0xf6, 0x2b, 0x95, 0x99, 0xd5, 0x53, 0x18, 0x2a, 0x64, 0x29, 0xbd, 0xee, 0xb7,
	0x4d, 0xbd, 0x7b, 0x5e, 0xc2, 0x9c, 0x69, 0x64, 0xfa, 0x22, 0xa1, 0x29, 0xcd, 0xce, 0x52, 0x65,
	0xb7, 0xf1, 0xda, 0xa5, 0xca, 0x0c, 0xf9, 0x97, 0xff, 0x16, 0x38, 0xdb, 0x63, 0xce, 0x7e, 0x98,
	0xe7, 0x27, 0xdf, 0x60, 0x14, 0x6c, 0xe8, 0x35, 0x6c, 0xf2, 0xd6, 0x17, 0xb1, 0xdf, 0x7a, 0xf9,
	0xd9, 0x1d, 0xa4, 0xbc, 0x0e, 0xf9, 0x0c, 0xe3, 0x4d, 0x40, 0x6f, 0x52, 0x22, 0xc4, 0xb4, 0xb5,
	0x63, 0x9b, 0x39, 0x06, 0x5b, 0x96, 0x42, 0x57, 0x5e, 0x87, 0x7c, 0x04, 0x30, 0x23, 0x8d, 0x73,
	0x32, 0xae, 0xdb, 0x2f, 0x31, 0xb4, 0x5a, 0x7f, 0xda, 0xbf, 0xfa, 0xfe, 0xa7, 0xef, 0x22, 0x8e,
	0x07, 0xf5, 0x6f, 0xfc, 0xfa, 0x10, 0x00, 0x00, 0xff, 0xff, 0x96, 0xb8, 0xb6, 0x46, 0xb3, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwinAgoraClient is the client API for TwinAgora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwinAgoraClient interface {
	CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*CallPeopleRes, error)
	SC_PeopleEntry(ctx context.Context, in *PeopleEntryRes, opts ...grpc.CallOption) (*Empty, error)
	SC_PushMsg(ctx context.Context, in *PushMsgRes, opts ...grpc.CallOption) (*Empty, error)
}

type twinAgoraClient struct {
	cc *grpc.ClientConn
}

func NewTwinAgoraClient(cc *grpc.ClientConn) TwinAgoraClient {
	return &twinAgoraClient{cc}
}

func (c *twinAgoraClient) CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*CallPeopleRes, error) {
	out := new(CallPeopleRes)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PeopleEntry(ctx context.Context, in *PeopleEntryRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PeopleEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PushMsg(ctx context.Context, in *PushMsgRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinAgoraServer is the server API for TwinAgora service.
type TwinAgoraServer interface {
	CS_CallPeople(context.Context, *CallPeopleReq) (*CallPeopleRes, error)
	SC_PeopleEntry(context.Context, *PeopleEntryRes) (*Empty, error)
	SC_PushMsg(context.Context, *PushMsgRes) (*Empty, error)
}

// UnimplementedTwinAgoraServer can be embedded to have forward compatible implementations.
type UnimplementedTwinAgoraServer struct {
}

func (*UnimplementedTwinAgoraServer) CS_CallPeople(ctx context.Context, req *CallPeopleReq) (*CallPeopleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_CallPeople not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_PeopleEntry(ctx context.Context, req *PeopleEntryRes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_PeopleEntry not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_PushMsg(ctx context.Context, req *PushMsgRes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_PushMsg not implemented")
}

func RegisterTwinAgoraServer(s *grpc.Server, srv TwinAgoraServer) {
	s.RegisterService(&_TwinAgora_serviceDesc, srv)
}

func _TwinAgora_CS_CallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, req.(*CallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PeopleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleEntryRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PeopleEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, req.(*PeopleEntryRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PushMsg(ctx, req.(*PushMsgRes))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwinAgora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TwinAgora",
	HandlerType: (*TwinAgoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CS_CallPeople",
			Handler:    _TwinAgora_CS_CallPeople_Handler,
		},
		{
			MethodName: "SC_PeopleEntry",
			Handler:    _TwinAgora_SC_PeopleEntry_Handler,
		},
		{
			MethodName: "SC_PushMsg",
			Handler:    _TwinAgora_SC_PushMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twin_agora.proto",
}
