// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twin_agora.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//S端推送给C端一些事件
type PushMsg struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Uid                  int32    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               string   `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventId              int32    `protobuf:"varint,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsg) Reset()         { *m = PushMsg{} }
func (m *PushMsg) String() string { return proto.CompactTextString(m) }
func (*PushMsg) ProtoMessage()    {}
func (*PushMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{0}
}

func (m *PushMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsg.Unmarshal(m, b)
}
func (m *PushMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsg.Marshal(b, m, deterministic)
}
func (m *PushMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsg.Merge(m, src)
}
func (m *PushMsg) XXX_Size() int {
	return xxx_messageInfo_PushMsg.Size(m)
}
func (m *PushMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsg proto.InternalMessageInfo

func (m *PushMsg) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *PushMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PushMsg) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PushMsg) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *PushMsg) GetEventId() int32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *PushMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//房间心跳
type RoomHeartbeatReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid                  int32    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomHeartbeatReq) Reset()         { *m = RoomHeartbeatReq{} }
func (m *RoomHeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*RoomHeartbeatReq) ProtoMessage()    {}
func (*RoomHeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{1}
}

func (m *RoomHeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomHeartbeatReq.Unmarshal(m, b)
}
func (m *RoomHeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomHeartbeatReq.Marshal(b, m, deterministic)
}
func (m *RoomHeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomHeartbeatReq.Merge(m, src)
}
func (m *RoomHeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_RoomHeartbeatReq.Size(m)
}
func (m *RoomHeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomHeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomHeartbeatReq proto.InternalMessageInfo

func (m *RoomHeartbeatReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *RoomHeartbeatReq) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RoomHeartbeatReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomHeartbeatReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

//呼叫某人，加入一个房间，进行：音视频通话
type CancelCallPeopleReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelCallPeopleReq) Reset()         { *m = CancelCallPeopleReq{} }
func (m *CancelCallPeopleReq) String() string { return proto.CompactTextString(m) }
func (*CancelCallPeopleReq) ProtoMessage()    {}
func (*CancelCallPeopleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{2}
}

func (m *CancelCallPeopleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCallPeopleReq.Unmarshal(m, b)
}
func (m *CancelCallPeopleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCallPeopleReq.Marshal(b, m, deterministic)
}
func (m *CancelCallPeopleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCallPeopleReq.Merge(m, src)
}
func (m *CancelCallPeopleReq) XXX_Size() int {
	return xxx_messageInfo_CancelCallPeopleReq.Size(m)
}
func (m *CancelCallPeopleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCallPeopleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCallPeopleReq proto.InternalMessageInfo

func (m *CancelCallPeopleReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CancelCallPeopleReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CancelCallPeopleReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//专家发出应答选择
type CallVote struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallVote) Reset()         { *m = CallVote{} }
func (m *CallVote) String() string { return proto.CompactTextString(m) }
func (*CallVote) ProtoMessage()    {}
func (*CallVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{3}
}

func (m *CallVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallVote.Unmarshal(m, b)
}
func (m *CallVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallVote.Marshal(b, m, deterministic)
}
func (m *CallVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallVote.Merge(m, src)
}
func (m *CallVote) XXX_Size() int {
	return xxx_messageInfo_CallVote.Size(m)
}
func (m *CallVote) XXX_DiscardUnknown() {
	xxx_messageInfo_CallVote.DiscardUnknown(m)
}

var xxx_messageInfo_CallVote proto.InternalMessageInfo

func (m *CallVote) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallVote) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallVote) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//呼叫某人，加入一个房间，进行：音视频通话
type CallPeopleReq struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	PeopleType           int32    `protobuf:"varint,5,opt,name=people_type,json=peopleType,proto3" json:"people_type,omitempty"`
	PeopleRole           int32    `protobuf:"varint,6,opt,name=people_role,json=peopleRole,proto3" json:"people_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleReq) Reset()         { *m = CallPeopleReq{} }
func (m *CallPeopleReq) String() string { return proto.CompactTextString(m) }
func (*CallPeopleReq) ProtoMessage()    {}
func (*CallPeopleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{4}
}

func (m *CallPeopleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleReq.Unmarshal(m, b)
}
func (m *CallPeopleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleReq.Marshal(b, m, deterministic)
}
func (m *CallPeopleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleReq.Merge(m, src)
}
func (m *CallPeopleReq) XXX_Size() int {
	return xxx_messageInfo_CallPeopleReq.Size(m)
}
func (m *CallPeopleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleReq proto.InternalMessageInfo

func (m *CallPeopleReq) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallPeopleReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallPeopleReq) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *CallPeopleReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleReq) GetPeopleType() int32 {
	if m != nil {
		return m.PeopleType
	}
	return 0
}

func (m *CallPeopleReq) GetPeopleRole() int32 {
	if m != nil {
		return m.PeopleRole
	}
	return 0
}

//给发发起呼叫者，做出应答
type CallPeopleRes struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	ReceiveUid           string   `protobuf:"bytes,2,opt,name=receive_uid,json=receiveUid,proto3" json:"receive_uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	ErrCode              int32    `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	RoomId               string   `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallPeopleRes) Reset()         { *m = CallPeopleRes{} }
func (m *CallPeopleRes) String() string { return proto.CompactTextString(m) }
func (*CallPeopleRes) ProtoMessage()    {}
func (*CallPeopleRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{5}
}

func (m *CallPeopleRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallPeopleRes.Unmarshal(m, b)
}
func (m *CallPeopleRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallPeopleRes.Marshal(b, m, deterministic)
}
func (m *CallPeopleRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallPeopleRes.Merge(m, src)
}
func (m *CallPeopleRes) XXX_Size() int {
	return xxx_messageInfo_CallPeopleRes.Size(m)
}
func (m *CallPeopleRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CallPeopleRes.DiscardUnknown(m)
}

var xxx_messageInfo_CallPeopleRes proto.InternalMessageInfo

func (m *CallPeopleRes) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallPeopleRes) GetReceiveUid() string {
	if m != nil {
		return m.ReceiveUid
	}
	return ""
}

func (m *CallPeopleRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CallPeopleRes) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CallPeopleRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CallPeopleRes) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//某人进入了一个房间/频道，通知给C端
type PeopleEntry struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	RoomId               string   `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleEntry) Reset()         { *m = PeopleEntry{} }
func (m *PeopleEntry) String() string { return proto.CompactTextString(m) }
func (*PeopleEntry) ProtoMessage()    {}
func (*PeopleEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{6}
}

func (m *PeopleEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleEntry.Unmarshal(m, b)
}
func (m *PeopleEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleEntry.Marshal(b, m, deterministic)
}
func (m *PeopleEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleEntry.Merge(m, src)
}
func (m *PeopleEntry) XXX_Size() int {
	return xxx_messageInfo_PeopleEntry.Size(m)
}
func (m *PeopleEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleEntry proto.InternalMessageInfo

func (m *PeopleEntry) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *PeopleEntry) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PeopleEntry) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PeopleEntry) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//某人进入了一个房间/频道，通知给C端
type PeopleLeaveRes struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	RoomId               string   `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleLeaveRes) Reset()         { *m = PeopleLeaveRes{} }
func (m *PeopleLeaveRes) String() string { return proto.CompactTextString(m) }
func (*PeopleLeaveRes) ProtoMessage()    {}
func (*PeopleLeaveRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{7}
}

func (m *PeopleLeaveRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleLeaveRes.Unmarshal(m, b)
}
func (m *PeopleLeaveRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleLeaveRes.Marshal(b, m, deterministic)
}
func (m *PeopleLeaveRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleLeaveRes.Merge(m, src)
}
func (m *PeopleLeaveRes) XXX_Size() int {
	return xxx_messageInfo_PeopleLeaveRes.Size(m)
}
func (m *PeopleLeaveRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleLeaveRes.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleLeaveRes proto.InternalMessageInfo

func (m *PeopleLeaveRes) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *PeopleLeaveRes) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PeopleLeaveRes) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PeopleLeaveRes) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//给某人推送一条消息
type CallReply struct {
	SourceUid            int32    `protobuf:"varint,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	SendUid              int32    `protobuf:"varint,2,opt,name=send_uid,json=sendUid,proto3" json:"send_uid,omitempty"`
	TargetUid            int32    `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MsgType              int32    `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	RoomId               string   `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallReply) Reset()         { *m = CallReply{} }
func (m *CallReply) String() string { return proto.CompactTextString(m) }
func (*CallReply) ProtoMessage()    {}
func (*CallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_223ae5106ca5efe7, []int{8}
}

func (m *CallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallReply.Unmarshal(m, b)
}
func (m *CallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallReply.Marshal(b, m, deterministic)
}
func (m *CallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallReply.Merge(m, src)
}
func (m *CallReply) XXX_Size() int {
	return xxx_messageInfo_CallReply.Size(m)
}
func (m *CallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CallReply.DiscardUnknown(m)
}

var xxx_messageInfo_CallReply proto.InternalMessageInfo

func (m *CallReply) GetSourceUid() int32 {
	if m != nil {
		return m.SourceUid
	}
	return 0
}

func (m *CallReply) GetSendUid() int32 {
	if m != nil {
		return m.SendUid
	}
	return 0
}

func (m *CallReply) GetTargetUid() int32 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *CallReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CallReply) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *CallReply) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func init() {
	proto.RegisterType((*PushMsg)(nil), "pb.PushMsg")
	proto.RegisterType((*RoomHeartbeatReq)(nil), "pb.RoomHeartbeatReq")
	proto.RegisterType((*CancelCallPeopleReq)(nil), "pb.CancelCallPeopleReq")
	proto.RegisterType((*CallVote)(nil), "pb.CallVote")
	proto.RegisterType((*CallPeopleReq)(nil), "pb.CallPeopleReq")
	proto.RegisterType((*CallPeopleRes)(nil), "pb.CallPeopleRes")
	proto.RegisterType((*PeopleEntry)(nil), "pb.PeopleEntry")
	proto.RegisterType((*PeopleLeaveRes)(nil), "pb.PeopleLeaveRes")
	proto.RegisterType((*CallReply)(nil), "pb.CallReply")
}

func init() { proto.RegisterFile("twin_agora.proto", fileDescriptor_223ae5106ca5efe7) }

var fileDescriptor_223ae5106ca5efe7 = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x6e, 0x7e, 0x8d, 0x27, 0x40, 0xc3, 0x82, 0x44, 0x40, 0x42, 0x20, 0x1f, 0x2a, 0xd4, 0x43,
	0xe8, 0x8f, 0x7a, 0xe2, 0x44, 0x5d, 0xa4, 0x22, 0xb5, 0x12, 0x72, 0xa0, 0x87, 0x5e, 0x2c, 0xc7,
	0x9e, 0x1a, 0x4b, 0xf6, 0xee, 0xb2, 0x5e, 0x40, 0x79, 0x97, 0x3e, 0x45, 0x0f, 0xbd, 0xf4, 0xd9,
	0x2a, 0x55, 0xbb, 0x76, 0x88, 0x37, 0x69, 0x48, 0x68, 0xb9, 0xed, 0xcc, 0xce, 0x37, 0xf3, 0x79,
	0xe6, 0xf3, 0x2c, 0x74, 0xe5, 0x5d, 0x42, 0xfd, 0x20, 0x66, 0x22, 0xe8, 0x73, 0xc1, 0x24, 0x23,
	0x75, 0x3e, 0xdc, 0x5d, 0x0d, 0x59, 0x96, 0x31, 0x5a, 0x78, 0x9c, 0xef, 0x35, 0xb0, 0xce, 0x6f,
	0xf2, 0xab, 0xcf, 0x79, 0x4c, 0xf6, 0x00, 0x72, 0x76, 0x23, 0x42, 0xf4, 0x6f, 0x92, 0xa8, 0x57,
	0x3b, 0xa8, 0x1d, 0xb6, 0x3c, 0xbb, 0xf0, 0x5c, 0x26, 0x11, 0x21, 0xd0, 0x0c, 0x59, 0x84, 0xbd,
	0xba, 0xbe, 0xd0, 0x67, 0xd2, 0x85, 0x86, 0x8a, 0x6d, 0x68, 0x97, 0x3a, 0x92, 0x6d, 0xb0, 0x04,
	0x63, 0x99, 0x9f, 0x44, 0xbd, 0xe6, 0x41, 0xed, 0xd0, 0xf6, 0xda, 0xca, 0x3c, 0x8b, 0xc8, 0x0e,
	0xac, 0xe0, 0x2d, 0x52, 0xa9, 0x6e, 0x5a, 0x3a, 0xde, 0xd2, 0xf6, 0x59, 0x44, 0x7a, 0x60, 0x85,
	0x8c, 0x4a, 0xa4, 0xb2, 0xd7, 0xd6, 0x98, 0xb1, 0xe9, 0x70, 0xe8, 0x7a, 0x8c, 0x65, 0x1f, 0x31,
	0x10, 0x72, 0x88, 0x81, 0xf4, 0xf0, 0x7a, 0x09, 0x9a, 0x32, 0xc9, 0x0a, 0x9a, 0x0d, 0x4f, 0x9f,
	0xab, 0xa4, 0x1a, 0x06, 0xa9, 0x92, 0x7f, 0xf3, 0x9e, 0xbf, 0xe3, 0xc3, 0xa6, 0x1b, 0xd0, 0x10,
	0x53, 0x37, 0x48, 0xd3, 0x73, 0x64, 0x3c, 0xc5, 0x25, 0x8a, 0x96, 0x79, 0xea, 0x7f, 0xed, 0x83,
	0x51, 0xd2, 0xb9, 0x80, 0x15, 0x95, 0xfa, 0x0b, 0x93, 0xf8, 0x84, 0x59, 0x7f, 0xd5, 0x60, 0xed,
	0x3f, 0x19, 0xef, 0x01, 0xc8, 0x40, 0xc4, 0x28, 0xfd, 0xc9, 0x48, 0xed, 0xc2, 0xa3, 0x00, 0x6a,
	0x48, 0x57, 0x01, 0xa5, 0x98, 0x96, 0x83, 0x1d, 0x9b, 0x64, 0x1f, 0x3a, 0x5c, 0x97, 0xf5, 0xe5,
	0x88, 0x63, 0x39, 0x5c, 0x28, 0x5c, 0x17, 0x23, 0x8e, 0x95, 0x00, 0xc1, 0x52, 0xd4, 0x33, 0xbe,
	0x0f, 0xf0, 0x58, 0x8a, 0xce, 0xcf, 0x29, 0xf6, 0xf9, 0x22, 0xf6, 0xfb, 0xd0, 0x11, 0x18, 0x62,
	0x72, 0x5b, 0xdc, 0xd7, 0x35, 0x21, 0x28, 0x5d, 0x53, 0x6c, 0x1b, 0x26, 0x5b, 0xa5, 0x43, 0x21,
	0x7c, 0x2d, 0xe5, 0x66, 0xa9, 0x43, 0x21, 0x5c, 0xa5, 0xe6, 0x6d, 0x50, 0x47, 0x3f, 0xcb, 0x63,
	0xfd, 0x11, 0xb6, 0xd7, 0x46, 0x21, 0xd4, 0x9f, 0x51, 0x69, 0x7b, 0xdb, 0x68, 0xfb, 0x35, 0x74,
	0x0a, 0xce, 0xa7, 0x54, 0x8a, 0xd1, 0xe3, 0x7b, 0x3e, 0x9f, 0xe6, 0xbc, 0xff, 0xc8, 0x91, 0xb0,
	0x5e, 0x94, 0xfc, 0x84, 0xc1, 0xed, 0x32, 0xbd, 0x7a, 0x92, 0xaa, 0x3f, 0x6a, 0x60, 0xab, 0x09,
	0x79, 0xc8, 0xd3, 0x85, 0xdf, 0xb9, 0x03, 0x2b, 0x39, 0xd2, 0xc8, 0x9f, 0x94, 0xb5, 0x94, 0x7d,
	0xb9, 0x9c, 0xc8, 0xca, 0x4d, 0xd0, 0x34, 0x36, 0x81, 0xca, 0x99, 0xe5, 0x71, 0x55, 0x61, 0x56,
	0x96, 0xc7, 0x5a, 0x5e, 0xf3, 0xa6, 0xf3, 0xe6, 0x77, 0x0b, 0xec, 0x8b, 0xbb, 0x84, 0x9e, 0xa8,
	0x15, 0x48, 0x8e, 0x60, 0xcd, 0x1d, 0xf8, 0x13, 0x99, 0x91, 0x8d, 0x3e, 0x1f, 0xf6, 0x8d, 0x9f,
	0x66, 0xd7, 0x56, 0xae, 0xd3, 0x8c, 0xcb, 0x91, 0xf3, 0x4c, 0x01, 0x06, 0xee, 0x83, 0x80, 0xdc,
	0x04, 0x1c, 0xc3, 0xa6, 0xae, 0x60, 0xae, 0x0f, 0xb2, 0x5d, 0xc0, 0x66, 0x96, 0xca, 0x0c, 0x58,
	0x57, 0xfb, 0x27, 0x70, 0x1f, 0xd6, 0xdd, 0x81, 0x5f, 0x95, 0xe2, 0x73, 0x75, 0x5d, 0x71, 0xcc,
	0xc4, 0x0f, 0xdc, 0x47, 0xc4, 0xbf, 0xae, 0xe4, 0xd7, 0xba, 0x23, 0x64, 0x12, 0x3f, 0x16, 0xe2,
	0x0c, 0xe4, 0xbe, 0xc4, 0x92, 0x90, 0x97, 0xb0, 0x5a, 0x36, 0xbc, 0x90, 0xd9, 0xda, 0xb8, 0xdf,
	0xda, 0x9c, 0x4e, 0xbf, 0x65, 0x4c, 0xf3, 0x24, 0x0c, 0xf1, 0x1b, 0x97, 0x64, 0x75, 0x8c, 0x51,
	0x0b, 0xd6, 0x84, 0xbc, 0x2a, 0x3b, 0x5c, 0x85, 0x3c, 0x8c, 0xe8, 0xc3, 0x86, 0x51, 0xe4, 0x03,
	0xd2, 0xd1, 0x82, 0x78, 0xa3, 0xc2, 0xa2, 0xf8, 0x77, 0xd0, 0x75, 0x07, 0xbe, 0xf1, 0xc2, 0x91,
	0x2d, 0x15, 0x30, 0xfd, 0xe8, 0x99, 0xb0, 0x17, 0x00, 0xaa, 0xb5, 0xe5, 0xb3, 0xdd, 0xd1, 0x6d,
	0x2d, 0x0c, 0x23, 0xee, 0xbd, 0xf5, 0xb5, 0xd5, 0x3f, 0x3a, 0xe6, 0xc3, 0x61, 0x5b, 0x3f, 0xf6,
	0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x82, 0x3e, 0xe8, 0x43, 0x12, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwinAgoraClient is the client API for TwinAgora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwinAgoraClient interface {
	CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeople(ctx context.Context, in *CallPeopleRes, opts ...grpc.CallOption) (*Empty, error)
	CS_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	SC_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error)
	CS_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error)
	SC_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error)
	CS_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error)
	SC_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error)
	SC_CallReply(ctx context.Context, in *CallReply, opts ...grpc.CallOption) (*Empty, error)
	CS_CallPeopleAccefpt(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	CS_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	SC_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error)
	CS_RoomHeartbeat(ctx context.Context, in *RoomHeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
	SC_PushMsg(ctx context.Context, in *PushMsg, opts ...grpc.CallOption) (*Empty, error)
}

type twinAgoraClient struct {
	cc *grpc.ClientConn
}

func NewTwinAgoraClient(cc *grpc.ClientConn) TwinAgoraClient {
	return &twinAgoraClient{cc}
}

func (c *twinAgoraClient) CS_CallPeople(ctx context.Context, in *CallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeople(ctx context.Context, in *CallPeopleRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CancelCallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CancelCallPeople(ctx context.Context, in *CancelCallPeopleReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CancelCallPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_PeopleEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PeopleEntry(ctx context.Context, in *PeopleEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PeopleEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_PeopleLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PeopleLeave(ctx context.Context, in *PeopleLeaveRes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PeopleLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallReply(ctx context.Context, in *CallReply, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CallPeopleAccefpt(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeopleAccefpt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeopleAccept(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeopleAccept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_CallPeopleDeny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_CallPeopleDeny(ctx context.Context, in *CallVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_CallPeopleDeny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) CS_RoomHeartbeat(ctx context.Context, in *RoomHeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/CS_RoomHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinAgoraClient) SC_PushMsg(ctx context.Context, in *PushMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.TwinAgora/SC_PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinAgoraServer is the server API for TwinAgora service.
type TwinAgoraServer interface {
	CS_CallPeople(context.Context, *CallPeopleReq) (*Empty, error)
	SC_CallPeople(context.Context, *CallPeopleRes) (*Empty, error)
	CS_CancelCallPeople(context.Context, *CancelCallPeopleReq) (*Empty, error)
	SC_CancelCallPeople(context.Context, *CancelCallPeopleReq) (*Empty, error)
	CS_PeopleEntry(context.Context, *PeopleEntry) (*Empty, error)
	SC_PeopleEntry(context.Context, *PeopleEntry) (*Empty, error)
	CS_PeopleLeave(context.Context, *PeopleLeaveRes) (*Empty, error)
	SC_PeopleLeave(context.Context, *PeopleLeaveRes) (*Empty, error)
	SC_CallReply(context.Context, *CallReply) (*Empty, error)
	CS_CallPeopleAccefpt(context.Context, *CallVote) (*Empty, error)
	SC_CallPeopleAccept(context.Context, *CallVote) (*Empty, error)
	CS_CallPeopleDeny(context.Context, *CallVote) (*Empty, error)
	SC_CallPeopleDeny(context.Context, *CallVote) (*Empty, error)
	CS_RoomHeartbeat(context.Context, *RoomHeartbeatReq) (*Empty, error)
	SC_PushMsg(context.Context, *PushMsg) (*Empty, error)
}

// UnimplementedTwinAgoraServer can be embedded to have forward compatible implementations.
type UnimplementedTwinAgoraServer struct {
}

func (*UnimplementedTwinAgoraServer) CS_CallPeople(ctx context.Context, req *CallPeopleReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_CallPeople not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_CallPeople(ctx context.Context, req *CallPeopleRes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_CallPeople not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_CancelCallPeople(ctx context.Context, req *CancelCallPeopleReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_CancelCallPeople not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_CancelCallPeople(ctx context.Context, req *CancelCallPeopleReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_CancelCallPeople not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_PeopleEntry(ctx context.Context, req *PeopleEntry) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_PeopleEntry not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_PeopleEntry(ctx context.Context, req *PeopleEntry) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_PeopleEntry not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_PeopleLeave(ctx context.Context, req *PeopleLeaveRes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_PeopleLeave not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_PeopleLeave(ctx context.Context, req *PeopleLeaveRes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_PeopleLeave not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_CallReply(ctx context.Context, req *CallReply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_CallReply not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_CallPeopleAccefpt(ctx context.Context, req *CallVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_CallPeopleAccefpt not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_CallPeopleAccept(ctx context.Context, req *CallVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_CallPeopleAccept not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_CallPeopleDeny(ctx context.Context, req *CallVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_CallPeopleDeny not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_CallPeopleDeny(ctx context.Context, req *CallVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_CallPeopleDeny not implemented")
}
func (*UnimplementedTwinAgoraServer) CS_RoomHeartbeat(ctx context.Context, req *RoomHeartbeatReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CS_RoomHeartbeat not implemented")
}
func (*UnimplementedTwinAgoraServer) SC_PushMsg(ctx context.Context, req *PushMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SC_PushMsg not implemented")
}

func RegisterTwinAgoraServer(s *grpc.Server, srv TwinAgoraServer) {
	s.RegisterService(&_TwinAgora_serviceDesc, srv)
}

func _TwinAgora_CS_CallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeople(ctx, req.(*CallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPeopleRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeople(ctx, req.(*CallPeopleRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CancelCallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CancelCallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CancelCallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CancelCallPeople(ctx, req.(*CancelCallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CancelCallPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallPeopleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CancelCallPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CancelCallPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CancelCallPeople(ctx, req.(*CancelCallPeopleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_PeopleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_PeopleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_PeopleEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_PeopleEntry(ctx, req.(*PeopleEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PeopleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PeopleEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PeopleEntry(ctx, req.(*PeopleEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_PeopleLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleLeaveRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_PeopleLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_PeopleLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_PeopleLeave(ctx, req.(*PeopleLeaveRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PeopleLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleLeaveRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PeopleLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PeopleLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PeopleLeave(ctx, req.(*PeopleLeaveRes))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallReply(ctx, req.(*CallReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CallPeopleAccefpt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeopleAccefpt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeopleAccefpt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeopleAccefpt(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeopleAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeopleAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeopleAccept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeopleAccept(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_CallPeopleDeny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_CallPeopleDeny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_CallPeopleDeny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_CallPeopleDeny(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_CallPeopleDeny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_CallPeopleDeny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_CallPeopleDeny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_CallPeopleDeny(ctx, req.(*CallVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_CS_RoomHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).CS_RoomHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/CS_RoomHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).CS_RoomHeartbeat(ctx, req.(*RoomHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwinAgora_SC_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinAgoraServer).SC_PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwinAgora/SC_PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinAgoraServer).SC_PushMsg(ctx, req.(*PushMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwinAgora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TwinAgora",
	HandlerType: (*TwinAgoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CS_CallPeople",
			Handler:    _TwinAgora_CS_CallPeople_Handler,
		},
		{
			MethodName: "SC_CallPeople",
			Handler:    _TwinAgora_SC_CallPeople_Handler,
		},
		{
			MethodName: "CS_CancelCallPeople",
			Handler:    _TwinAgora_CS_CancelCallPeople_Handler,
		},
		{
			MethodName: "SC_CancelCallPeople",
			Handler:    _TwinAgora_SC_CancelCallPeople_Handler,
		},
		{
			MethodName: "CS_PeopleEntry",
			Handler:    _TwinAgora_CS_PeopleEntry_Handler,
		},
		{
			MethodName: "SC_PeopleEntry",
			Handler:    _TwinAgora_SC_PeopleEntry_Handler,
		},
		{
			MethodName: "CS_PeopleLeave",
			Handler:    _TwinAgora_CS_PeopleLeave_Handler,
		},
		{
			MethodName: "SC_PeopleLeave",
			Handler:    _TwinAgora_SC_PeopleLeave_Handler,
		},
		{
			MethodName: "SC_CallReply",
			Handler:    _TwinAgora_SC_CallReply_Handler,
		},
		{
			MethodName: "CS_CallPeopleAccefpt",
			Handler:    _TwinAgora_CS_CallPeopleAccefpt_Handler,
		},
		{
			MethodName: "SC_CallPeopleAccept",
			Handler:    _TwinAgora_SC_CallPeopleAccept_Handler,
		},
		{
			MethodName: "CS_CallPeopleDeny",
			Handler:    _TwinAgora_CS_CallPeopleDeny_Handler,
		},
		{
			MethodName: "SC_CallPeopleDeny",
			Handler:    _TwinAgora_SC_CallPeopleDeny_Handler,
		},
		{
			MethodName: "CS_RoomHeartbeat",
			Handler:    _TwinAgora_CS_RoomHeartbeat_Handler,
		},
		{
			MethodName: "SC_PushMsg",
			Handler:    _TwinAgora_SC_PushMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twin_agora.proto",
}
