// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "header.BaseInfo-demo:{   \"app_version\": \"v1.1.1\",   \"device\": \"iphone\",   \"device_id\": \"aaaaaaaa\",   \"device_version\": \"12\",   \"dpi\": \"390x844\",   \"ip\": \"127.0.0.1\",   \"lat\": \"21.1111\",   \"lon\": \"32.4444\",   \"os\": 1,   \"os_version\": \"11\",   \"referer\": \"\" }"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/base/captcha": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "防止有人恶意攻击，尝试破解密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "生成图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "default": "11",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.SysCaptchaResponse"
                        }
                    }
                }
            }
        },
        "/base/checkMobileExist": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "测试是否已存在",
                "parameters": [
                    {
                        "type": "string",
                        "default": "11",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CheckMobileExist"
                        }
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "true:存在 false:不存在",
                        "schema": {
                            "type": "bool"
                        }
                    }
                }
            }
        },
        "/base/constList": {
            "get": {
                "description": "所有常量列表，方便调用与调试",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "所有常量列表",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/base/headerStruct": {
            "get": {
                "description": "日常header里放一诸如验证类的东西，统一公示出来，仅是说明，方便测试，不是真实API，方便使用",
                "tags": [
                    "Base"
                ],
                "summary": "header头结构体",
                "parameters": [
                    {
                        "type": "string",
                        "default": "11",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "1",
                            "2",
                            "3",
                            "4"
                        ],
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/request.Header"
                        }
                    }
                }
            }
        },
        "/base/login": {
            "post": {
                "description": "用户登陆，验证，生成token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.LoginResponse"
                        }
                    }
                }
            }
        },
        "/base/loginSms": {
            "post": {
                "description": "用户登陆，验证，生成token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "短信登陆",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RLoginThird"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.LoginResponse"
                        }
                    }
                }
            }
        },
        "/base/loginThird": {
            "post": {
                "description": "用户登陆，验证，生成token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户登陆三方",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RLoginThird"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.LoginResponse"
                        }
                    }
                }
            }
        },
        "/base/parserToken": {
            "post": {
                "description": "应用接到token后，要到后端再统计认证一下，确保准确",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "解析一个TOKEN",
                "parameters": [
                    {
                        "description": "需要验证的token值",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ParserToken"
                        }
                    },
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/request.CustomClaims"
                        }
                    }
                }
            }
        },
        "/base/projectList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "每个项目的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "项目列表",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Project"
                        }
                    }
                }
            }
        },
        "/base/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户注册账号",
                "parameters": [
                    {
                        "type": "string",
                        "default": "11",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端基础信息(json格式,参考request.HeaderBaseInfo)",
                        "name": "X-Base-Info",
                        "in": "header"
                    },
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/base/registerSms": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户注册账号-通过手机验证码",
                "parameters": [
                    {
                        "type": "string",
                        "default": "11",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端基础信息(json格式,参考request.HeaderBaseInfo)",
                        "name": "X-Base-Info",
                        "in": "header"
                    },
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterSms"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/base/sendEmail": {
            "post": {
                "description": "登陆、注册、通知等发送",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "发送邮件",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "基础信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"发送成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/sendSms": {
            "post": {
                "description": "登陆/注册/找回密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "发送短信",
                "parameters": [
                    {
                        "enum": [
                            "11",
                            "12",
                            "21",
                            "22"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "X-Source-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "6",
                        "description": "项目ID",
                        "name": "X-Project-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "imzgoframe",
                        "description": "访问KEY",
                        "name": "X-Access",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendSMS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"发送成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sys/config": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Config",
                "parameters": [
                    {
                        "description": "用户名/密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SystemConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sys/quit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "关闭该服务进程",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Quit",
                "parameters": [
                    {
                        "description": "用户名/密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SystemConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/changePassword": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "用户名, 原密码, 新密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ChangePasswordStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/deleteUser": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/getUserInfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取当前登陆用户的基础信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/getUserList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "分页获取用户列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户退出",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户退出",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"退出成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/setUserInfo": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户信息",
                "parameters": [
                    {
                        "description": "ID, 用户名, 昵称, 头像链接",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SetUserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"设置成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "httpresponse.LoginResponse": {
            "description": "登陆成功返回结果",
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "token失效时间",
                    "type": "integer"
                },
                "is_new": {
                    "description": "重复登陆也可以成功，但返回的是旧的TOKEN，非新生成token",
                    "type": "boolean"
                },
                "is_new_reg": {
                    "description": "3方登陆时，为了简化操作，如果没注册将自动注册",
                    "type": "boolean"
                },
                "token": {
                    "description": "生成的token",
                    "type": "string"
                },
                "user": {
                    "description": "登陆成功结果响应",
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "httpresponse.Response": {
            "description": "公共HTTP响应结构体",
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码，200是OK，4代表有发生错误",
                    "type": "integer"
                },
                "data": {
                    "description": "请求时有数据返回，会在此字段中"
                },
                "msg": {
                    "description": "如果有错误会写在此，如果有些提示信息也会放在这里",
                    "type": "string"
                }
            }
        },
        "httpresponse.SysCaptchaResponse": {
            "description": "获取图片验证码",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "pic_content": {
                    "description": "图片内容,base64",
                    "type": "string"
                }
            }
        },
        "model.Project": {
            "description": "项目详情",
            "type": "object",
            "properties": {
                "access": {
                    "description": "简单baseAuth 认证KEY",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "deleted_at": {
                    "description": "是否删除",
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "desc": {
                    "description": "描述",
                    "type": "string"
                },
                "git": {
                    "description": "GIT代码仓URL地址",
                    "type": "string"
                },
                "id": {
                    "description": "自增ID",
                    "type": "integer"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "secret_key": {
                    "description": "密钥",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "type": {
                    "description": "类型",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "最后更新时间",
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "description": "用户基础信息",
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "出生日期,unix时间戳",
                    "type": "integer"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "deleted_at": {
                    "description": "是否删除",
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "headerImg": {
                    "description": "头像url地址",
                    "type": "string"
                },
                "id": {
                    "description": "自增ID",
                    "type": "integer"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "nick_name": {
                    "description": "昵称",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "recommend": {
                    "description": "推荐人",
                    "type": "string"
                },
                "robot": {
                    "description": "机器人",
                    "type": "integer"
                },
                "sex": {
                    "description": "性别1男2女",
                    "type": "integer"
                },
                "status": {
                    "description": "状态1正常2禁用",
                    "type": "integer"
                },
                "test": {
                    "description": "是否测试,1是2否",
                    "type": "integer"
                },
                "type": {
                    "description": "是否游客,1是2否",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "最后更新时间",
                    "type": "integer"
                },
                "username": {
                    "description": "用户登录名",
                    "type": "string"
                },
                "uuid": {
                    "description": "UID字条串化",
                    "type": "string"
                }
            }
        },
        "request.ChangePasswordStruct": {
            "description": "修改密码",
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.CheckMobileExist": {
            "type": "object",
            "properties": {
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "purpose": {
                    "description": "用途,1注册2找回密码3修改密码4修改邮箱5",
                    "type": "integer"
                }
            }
        },
        "request.CustomClaims": {
            "description": "jwt 容器内容",
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "nick_name": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目ID",
                    "type": "integer"
                },
                "source_type": {
                    "description": "来源",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.Header": {
            "description": "http客户端请求头",
            "type": "object",
            "properties": {
                "access": {
                    "description": "使用网关时，不允许随意访问，得有key",
                    "type": "string"
                },
                "auto_ip": {
                    "description": "获取不到请求方IP时，系统自动获取生成",
                    "type": "string"
                },
                "base_info": {
                    "description": "收集客户端的一些基础信息，json",
                    "$ref": "#/definitions/request.HeaderBaseInfo"
                },
                "project_id": {
                    "description": "项目ID，所有的服务/项目/前端/App，均要先向管理员申请一个账号，才能用于日常请求",
                    "type": "integer"
                },
                "request_id": {
                    "description": "每次请求的唯一标识，响应时也会返回，如果请求方没有，后端会默认生成一个",
                    "type": "string"
                },
                "source_type": {
                    "description": "请求方来源类型(pc h5 ios android vr spider unknow)，不同类型，不同JWT，原因：1手机端登陆后，PC端再登陆，互踢，无法共存。2越权，有些接口不允许互相访问",
                    "type": "integer"
                },
                "token": {
                    "description": "JWT用户登陆令牌(HS256 对称算法，共享一个密钥)",
                    "type": "string"
                },
                "trace_id": {
                    "description": "追踪ID，主要用于链路追踪，如果请求方没有，后端会默认生成一个，跟request略像，但给后端使用",
                    "type": "string"
                }
            }
        },
        "request.HeaderBaseInfo": {
            "description": "http客户端请求头-基础信息",
            "type": "object",
            "properties": {
                "app_version": {
                    "description": "app/前端/服务/项目 版本号",
                    "type": "string"
                },
                "device": {
                    "description": "ipad iphone huawei mi chrome firefox ie",
                    "type": "string"
                },
                "device_id": {
                    "description": "设备ID",
                    "type": "string"
                },
                "device_version": {
                    "description": "mi8 hongmi7 ios8 ios9 ie8 ie9",
                    "type": "string"
                },
                "dpi": {
                    "description": "分辨率",
                    "type": "string"
                },
                "ip": {
                    "description": "请求方的IP",
                    "type": "string"
                },
                "lat": {
                    "description": "纬度",
                    "type": "string"
                },
                "lon": {
                    "description": "经度",
                    "type": "string"
                },
                "os": {
                    "description": "win mac android ios",
                    "type": "integer"
                },
                "os_version": {
                    "description": "win7 win9 mac10 android9",
                    "type": "string"
                },
                "referer": {
                    "description": "页面来源",
                    "type": "string"
                }
            }
        },
        "request.Login": {
            "description": "正常登陆，需要用户名密码",
            "type": "object",
            "properties": {
                "captcha": {
                    "description": "验证码",
                    "type": "string"
                },
                "captchaId": {
                    "description": "验证码-ID",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名：普通字符串、手机号、邮箱",
                    "type": "string"
                }
            }
        },
        "request.PageInfo": {
            "description": "分页",
            "type": "object",
            "properties": {
                "page": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页多少条记录",
                    "type": "integer"
                }
            }
        },
        "request.ParserToken": {
            "description": "解析token",
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "request.RLoginThird": {
            "description": "3方登陆",
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "生日",
                    "type": "integer"
                },
                "channel": {
                    "description": "来源渠道",
                    "type": "integer"
                },
                "ext_diy": {
                    "description": "自定义用户属性，暂未实现",
                    "type": "string"
                },
                "guest": {
                    "description": "类型,1普通2游客",
                    "type": "integer"
                },
                "headerImg": {
                    "description": "头像地址",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "passWord": {
                    "description": "登陆密码 转md5存储",
                    "type": "string"
                },
                "platformType": {
                    "description": "3方平台类型",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目Id",
                    "type": "integer"
                },
                "recommend": {
                    "description": "推荐人",
                    "type": "string"
                },
                "sex": {
                    "description": "性别",
                    "type": "integer"
                },
                "thirdId": {
                    "description": "3方平台用户ID",
                    "type": "string"
                },
                "third_id": {
                    "description": "三方平台ID",
                    "type": "string"
                },
                "third_type": {
                    "description": "三方平台类型",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.Register": {
            "description": "注册信息",
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "生日",
                    "type": "integer"
                },
                "channel": {
                    "description": "来源渠道",
                    "type": "integer"
                },
                "ext_diy": {
                    "description": "自定义用户属性，暂未实现",
                    "type": "string"
                },
                "guest": {
                    "description": "类型,1普通2游客",
                    "type": "integer"
                },
                "headerImg": {
                    "description": "头像地址",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "passWord": {
                    "description": "登陆密码 转md5存储",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目Id",
                    "type": "integer"
                },
                "recommend": {
                    "description": "推荐人",
                    "type": "string"
                },
                "sex": {
                    "description": "性别",
                    "type": "integer"
                },
                "third_id": {
                    "description": "三方平台ID",
                    "type": "string"
                },
                "third_type": {
                    "description": "三方平台类型",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.RegisterSms": {
            "description": "注册信息 - 通过手机号",
            "type": "object",
            "properties": {
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目Id",
                    "type": "integer"
                },
                "sms_auth_code": {
                    "description": "短信验证码",
                    "type": "string"
                },
                "sms_rule_id": {
                    "description": "短信类型，登陆/注册",
                    "type": "integer"
                }
            }
        },
        "request.SendEmail": {
            "description": "发送邮件",
            "type": "object",
            "properties": {
                "carbon_copy": {
                    "description": "抄送，，email格式",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "receiver": {
                    "description": "接收者，email格式",
                    "type": "string"
                },
                "replaceVar": {
                    "description": "邮件内容模块中变量替换",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "rule_id": {
                    "description": "配置规则的ID",
                    "type": "integer"
                },
                "send_ip": {
                    "description": "发送者IP，如为空系统默认取：请求方的IP,最好给真实的，一但被刷，会使用此值",
                    "type": "string"
                },
                "send_uid": {
                    "description": "发送者ID，管理员是9999，未知8888",
                    "type": "integer"
                }
            }
        },
        "request.SendSMS": {
            "description": "发送验证码",
            "type": "object",
            "properties": {
                "receiver": {
                    "description": "接收者，email格式",
                    "type": "string"
                },
                "replace_var": {
                    "description": "邮件内容模块中变量替换",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "rule_id": {
                    "description": "配置规则的ID",
                    "type": "integer"
                },
                "send_ip": {
                    "description": "发送者IP，如为空系统默认取：请求方的IP,最好给真实的，一但被刷，会使用此值",
                    "type": "string"
                },
                "send_uid": {
                    "description": "发送者ID，管理员是9999，未知8888",
                    "type": "integer"
                }
            }
        },
        "request.SetUserInfo": {
            "description": "修改用户基础信息",
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "生日",
                    "type": "integer"
                },
                "headerImg": {
                    "description": "头像地址",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "sex": {
                    "description": "性别",
                    "type": "integer"
                }
            }
        },
        "request.SystemConfig": {
            "description": "系统管理员操作，需要2次验证",
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "不需要登陆，但是会验证头信息 , X-SourceType X-Access X-Project 等，(注：header 中的每个key X开头)",
            "name": "Base"
        },
        {
            "description": "用户相关操作(需要登陆，头里加X-Token = jwt)",
            "name": "User"
        }
    ]
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "0.1 测试版",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "z golang 框架",
	Description:      "restful api 工具，模拟客户端请求，方便调试/测试\n注：这只是一个工具，不是万能的，像：动态枚举类型、公共请求header、动态常量等\n详细的请去 <a href=\"http://127.0.0.1:6060\" target=\"_black\">godoc</a> 里去查看",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
