definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  httpresponse.LoginResponse:
    properties:
      expiresAt:
        description: token失效时间
        type: integer
      is_new:
        description: 重复登陆也可以成功，但返回的是旧的TOKEN，非新生成token
        type: boolean
      is_new_reg:
        description: 3方登陆时，为了简化操作，如果没注册将自动注册
        type: boolean
      token:
        description: 生成的token
        type: string
      user:
        $ref: '#/definitions/model.User'
        description: 用户基础信息
    type: object
  httpresponse.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  httpresponse.SysCaptchaResponse:
    properties:
      captchaId:
        type: string
      picPath:
        type: string
    type: object
  model.Project:
    properties:
      access:
        type: string
      created_at:
        type: integer
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        type: string
      git:
        type: string
      id:
        type: integer
      name:
        type: string
      secret_key:
        type: string
      status:
        type: integer
      type:
        type: integer
      updated_at:
        type: integer
    type: object
  model.User:
    properties:
      birthday:
        type: integer
      created_at:
        type: integer
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      headerImg:
        type: string
      id:
        type: integer
      mobile:
        description: ThirdId   string `json:"third_id" db:"define:varchar(50);comment:三方平台(登陆)用户ID;defaultValue:''"`
        type: string
      nick_name:
        type: string
      project_id:
        type: integer
      recommend:
        type: string
      robot:
        type: integer
      sex:
        type: integer
      status:
        type: integer
      type:
        type: integer
      updated_at:
        type: integer
      username:
        type: string
      uuid:
        type: string
    type: object
  request.ChangePasswordStruct:
    properties:
      newPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.CustomClaims:
    properties:
      aud:
        type: string
      exp:
        type: integer
      iat:
        type: integer
      id:
        type: integer
      iss:
        type: string
      jti:
        type: string
      nbf:
        type: integer
      nick_name:
        type: string
      project_id:
        description: |-
          AuthorityId string
          UUID        uuid.UUID
        type: integer
      source_type:
        type: integer
      sub:
        type: string
      username:
        type: string
    type: object
  request.GetById:
    properties:
      id:
        type: number
    type: object
  request.Header:
    properties:
      access:
        description: 使用网关时，不允许随意访问，得有key
        type: string
      auto_ip:
        description: 获取不到请求方IP时，系统自动获取生成
        type: string
      base_info:
        $ref: '#/definitions/request.HeaderBaseInfo'
        description: 收集客户端的一些基础信息，json
      project_id:
        description: 项目ID，所有的服务/项目/前端/App，均要先向管理员申请一个账号，才能用于日常请求
        type: integer
      request_id:
        description: 每次请求的唯一标识，响应时也会返回，如果请求方没有，后端会默认生成一个
        type: string
      source_type:
        description: 请求方来源类型(pc h5 ios android vr spider unknow)，不同类型，不同JWT，原因：1手机端登陆后，PC端再登陆，互踢，无法共存。2越权，有些接口不允许互相访问
        type: integer
      token:
        description: JWT用户登陆令牌(HS256 对称算法，共享一个密钥)
        type: string
      trace_id:
        description: 追踪ID，主要用于链路追踪，如果请求方没有，后端会默认生成一个，跟request略像，但给后端使用
        type: string
    type: object
  request.HeaderBaseInfo:
    properties:
      app_version:
        description: app/前端/服务/项目 版本号
        type: string
      device:
        description: ipad iphone huawei mi chrome firefox ie
        type: string
      device_id:
        description: 设备ID
        type: string
      device_version:
        description: mi8 hongmi7 ios8 ios9 ie8 ie9
        type: string
      dpi:
        description: 分辨率
        type: string
      ip:
        description: 请求方的IP
        type: string
      lat:
        description: 纬度
        type: string
      lon:
        description: 经度
        type: string
      os:
        description: win mac android ios
        type: integer
      os_version:
        description: win7 win9 mac10 android9
        type: string
      referer:
        description: 页面来源
        type: string
    type: object
  request.Login:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码-ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名：普通字符串、手机号、邮箱
        type: string
    type: object
  request.PageInfo:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  request.RLoginThird:
    properties:
      birthday:
        description: 生日
        type: integer
      channel:
        description: 来源渠道
        type: integer
      ext_diy:
        description: 自定义用户属性，暂未实现
        type: string
      guest:
        description: 类型,1普通2游客
        type: integer
      headerImg:
        description: 头像地址
        type: string
      nickName:
        description: 昵称
        type: string
      passWord:
        description: 登陆密码 转md5存储
        type: string
      platformType:
        type: integer
      project_id:
        description: 项目Id
        type: integer
      recommend:
        description: 推荐人
        type: string
      sex:
        description: 性别
        type: integer
      third_id:
        description: 三方平台ID
        type: string
      third_type:
        description: 三方平台类型
        type: integer
      thirdId:
        type: string
      userName:
        description: 用户名
        type: string
    type: object
  request.Register:
    properties:
      birthday:
        description: 生日
        type: integer
      channel:
        description: 来源渠道
        type: integer
      ext_diy:
        description: 自定义用户属性，暂未实现
        type: string
      guest:
        description: 类型,1普通2游客
        type: integer
      headerImg:
        description: 头像地址
        type: string
      nickName:
        description: 昵称
        type: string
      passWord:
        description: 登陆密码 转md5存储
        type: string
      project_id:
        description: 项目Id
        type: integer
      recommend:
        description: 推荐人
        type: string
      sex:
        description: 性别
        type: integer
      third_id:
        description: 三方平台ID
        type: string
      third_type:
        description: 三方平台类型
        type: integer
      userName:
        description: 用户名
        type: string
    type: object
  request.SetUserInfo:
    properties:
      birthday:
        description: 生日
        type: integer
      headerImg:
        description: 头像地址
        type: string
      nickName:
        description: 昵称
        type: string
      sex:
        description: 性别
        type: integer
    type: object
  request.SystemConfig:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.ParserTokenReq:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: restful api 工具，模拟客户端请求，方便调试/测试<br/>注：这只是一个工具，不是万能的，像：动态枚举类型、公共请求header、动态常量等<br/>详细的请去
    <a href="http://127.0.0.1:6060" target="_black">godoc</a> 里去查看
  license:
    name: '{   "app_version": "v1.1.1",   "device": "iphone",   "device_id": "aaaaaaaa",   "device_version":
      "12",   "dpi": "390x844",   "ip": "127.0.0.1",   "lat": "21.1111",   "lon":
      "32.4444",   "os": 1,   "os_version": "11",   "referer": "" }'
  title: z golang 框架
  version: 0.1 测试版
paths:
  /base/captcha:
    get:
      consumes:
      - application/json
      description: 防止有人恶意攻击，尝试破解密码
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.SysCaptchaResponse'
      security:
      - ApiKeyAuth: []
      summary: 生成图片验证码
      tags:
      - Base
  /base/constList:
    get:
      description: 常量列表
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: 所有常量列表
      tags:
      - Base
  /base/headerStruct:
    get:
      description: 日常header里放一诸如验证类的东西，统一公示出来，方便使用
      parameters:
      - description: 客户端基础信息
        in: body
        name: X-HeaderBaseInfo
        required: true
        schema:
          $ref: '#/definitions/request.HeaderBaseInfo'
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/request.Header'
      summary: header头结构体
      tags:
      - Base
  /base/login:
    post:
      description: 用户登陆，验证，生成token
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.LoginResponse'
      summary: 用户登陆
      tags:
      - Base
  /base/loginThird:
    post:
      description: 用户登陆，验证，生成token
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RLoginThird'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.LoginResponse'
      summary: 用户登陆三方
      tags:
      - Base
  /base/parserToken:
    post:
      description: 应用接到token后，要到后端再统计认证一下，确保准确
      parameters:
      - description: 需要验证的token值
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.ParserTokenReq'
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/request.CustomClaims'
      summary: 解析一个TOKEN
      tags:
      - Base
  /base/projectList:
    post:
      description: 每个项目的详细信息
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      security:
      - ApiKeyAuth: []
      summary: 项目列表
      tags:
      - Base
  /base/register:
    post:
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      - description: 客户端基础信息(json格式,参考request.HeaderBaseInfo)
        in: header
        name: X-Base-Info
        type: string
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 用户注册账号
      tags:
      - Base
  /base/sendSMS:
    post:
      description: 登陆、注册、通知等发送短信
      parameters:
      - default: "11"
        description: 来源
        in: header
        name: X-Source-Type
        required: true
        type: string
      - default: "6"
        description: 项目ID
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
        in: header
        name: X-Project-Id
        required: true
        type: string
      - default: imzgoframe
        description: 访问KEY
        in: header
        name: X-Access
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"发送成功"}'
          schema:
            type: string
      summary: 发送验证码
      tags:
      - Base
  /sys/config:
    post:
      description: Config
      parameters:
      - description: 用户名/密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SystemConfig'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Config
      tags:
      - System
  /sys/quit:
    post:
      description: 关闭该服务进程
      parameters:
      - description: 用户名/密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SystemConfig'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Quit
      tags:
      - System
  /user/changePassword:
    put:
      parameters:
      - description: 用户名, 原密码, 新密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ChangePasswordStruct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户修改密码
      tags:
      - User
  /user/deleteUser:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetById'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"删除成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - User
  /user/getUserInfo:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取当前登陆用户的基础信息
      tags:
      - User
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - User
  /user/logout:
    post:
      description: 用户退出
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"退出成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户退出
      tags:
      - User
  /user/setUserInfo:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID, 用户名, 昵称, 头像链接
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SetUserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"设置成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 设置用户信息
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
