definitions:
  model.SysAuthority:
    properties:
      authorityId:
        type: string
      authorityName:
        type: string
      children:
        items:
          $ref: '#/definitions/model.SysAuthority'
        type: array
      createdAt:
        type: string
      dataAuthorityId:
        items:
          $ref: '#/definitions/model.SysAuthority'
        type: array
      defaultRouter:
        type: string
      deletedAt:
        type: string
      menus:
        items:
          $ref: '#/definitions/model.SysBaseMenu'
        type: array
      parentId:
        type: string
      updatedAt:
        type: string
    type: object
  model.SysBaseMenu:
    properties:
      authoritys:
        items:
          $ref: '#/definitions/model.SysAuthority'
        type: array
      children:
        items:
          $ref: '#/definitions/model.SysBaseMenu'
        type: array
      component:
        type: string
      createdAt:
        type: integer
      defaultMenu:
        type: boolean
      hidden:
        type: boolean
      icon:
        type: string
      id:
        type: integer
      keepAlive:
        type: boolean
      name:
        type: string
      parameters:
        items:
          $ref: '#/definitions/model.SysBaseMenuParameter'
        type: array
      parentId:
        type: string
      path:
        type: string
      sort:
        type: integer
      title:
        type: string
      updatedAt:
        type: integer
    type: object
  model.SysBaseMenuParameter:
    properties:
      createdAt:
        type: integer
      id:
        type: integer
      key:
        type: string
      sysBaseMenuID:
        type: integer
      type:
        type: string
      updatedAt:
        type: integer
      value:
        type: string
    type: object
  model.User:
    properties:
      app_id:
        type: integer
      authority:
        $ref: '#/definitions/model.SysAuthority'
      authorityId:
        type: string
      birthday:
        type: integer
      createdAt:
        type: integer
      email:
        type: string
      headerImg:
        type: string
      id:
        type: integer
      mobile:
        type: string
      nickName:
        type: string
      robot:
        type: integer
      sex:
        type: integer
      status:
        type: integer
      updatedAt:
        type: integer
      userName:
        type: string
      uuid:
        type: string
    type: object
  request.ChangePasswordStruct:
    properties:
      newPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.GetById:
    properties:
      id:
        type: number
    type: object
  request.Login:
    properties:
      app_id:
        type: integer
      captcha:
        type: string
      captchaId:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.PageInfo:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  request.SendSMS:
    properties:
      app_id:
        type: string
      code:
        type: string
      mobile:
        type: string
      rule_id:
        type: integer
    type: object
  v1.LogData:
    properties:
      app_id:
        type: integer
      level:
        type: integer
      msg:
        type: string
      uid:
        type: integer
    type: object
info:
  contact: {}
  description: 拼装一个GO的基础框架方便日常使用
  title: z golang 框架
  version: "0.1"
paths:
  /base/captcha:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"验证码获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 生成图片验证码
      tags:
      - Base
  /base/checktoken:
    post:
      description: checktoken
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: checktoken
      tags:
      - User
  /base/login:
    post:
      description: 用户登陆，验证，生成token
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登陆
      tags:
      - Base
  /base/parserToken:
    post:
      description: ParserToken
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: ParserToken
      tags:
      - Base
  /base/register:
    post:
      parameters:
      - description: 用户名, 昵称, 密码, 角色ID ,AppId
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 用户注册账号
      tags:
      - User
  /base/sendSMS:
    post:
      description: 登陆、注册、通知等发送短信
      parameters:
      - description: 手机号, 规则ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendSMS'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"发送成功"}'
          schema:
            type: string
      summary: 发送验证码
      tags:
      - Base
  /logslave/getWsServer:
    get:
      description: 获取长连接API映射表
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      summary: 获取长连接API映射表
      tags:
      - Logslave
  /logslave/receive:
    post:
      parameters:
      - description: level,msg
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.LogData'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"已收录"}'
          schema:
            type: string
      summary: 接收日志
      tags:
      - Logslave
  /sys/config:
    post:
      description: Config
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Config
      tags:
      - User
  /sys/quit:
    post:
      description: Quit
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Quit
      tags:
      - User
  /user/changePassword:
    put:
      parameters:
      - description: 用户名, 原密码, 新密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ChangePasswordStruct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户修改密码
      tags:
      - User
  /user/deleteUser:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetById'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"删除成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - User
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - User
  /user/logout:
    post:
      description: 用户退出
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"退出成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户退出
      tags:
      - User
  /user/setUserInfo:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID, 用户名, 昵称, 头像链接
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"设置成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 设置用户信息
      tags:
      - User
swagger: "2.0"
