// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SAnBiIgcKBUVtcHR5IsQBCglIZWFydGJlYXQSEgoK",
            "c291cmNlX3VpZBgBIAEoBRIMCgR0aW1lGAIgASgDEhAKCHJlcV90aW1lGAMg",
            "ASgDEhcKD2NsaWVudF9yZXFfdGltZRgEIAEoAxIbChNjbGllbnRfcmVjZWl2",
            "ZV90aW1lGAUgASgDEhsKE3NlcnZlcl9yZWNlaXZlX3RpbWUYBiABKAMSHAoU",
            "c2VydmVyX3Jlc3BvbnNlX3RpbWUYByABKAMSEgoKcmVxdWVzdF9pZBgIIAEo",
            "CSJwCgxGRENsb3NlRXZlbnQSEgoKc291cmNlX3VpZBgBIAEoBRIPCgd1c2Vy",
            "X2lkGAIgASgFEg4KBnNvdXJjZRgDIAEoBRIUCgxjb250ZW50X3R5cGUYBCAB",
            "KAUSFQoNcHJvdG9jb2xfdHlwZRgFIAEoBSI0Cg1GRENyZWF0ZUV2ZW50EhIK",
            "CnNvdXJjZV91aWQYASABKAUSDwoHdXNlcl9pZBgCIAEoBSK0AQoHUGluZ1Jl",
            "cRISCgpzb3VyY2VfdWlkGAEgASgFEhIKCnJlcXVlc3RfaWQYAiABKAkSEAoI",
            "dHJhY2VfaWQYAyABKAkSFwoPY2xpZW50X3JlcV90aW1lGAQgASgDEhsKE2Ns",
            "aWVudF9yZWNlaXZlX3RpbWUYBSABKAMSGwoTc2VydmVyX3JlY2VpdmVfdGlt",
            "ZRgGIAEoAxIcChRzZXJ2ZXJfcmVzcG9uc2VfdGltZRgHIAEoAyK0AQoHUG9u",
            "Z1JlcxISCgpzb3VyY2VfdWlkGAEgASgFEhIKCnJlcXVlc3RfaWQYAiABKAkS",
            "EAoIdHJhY2VfaWQYAyABKAkSFwoPY2xpZW50X3JlcV90aW1lGAQgASgDEhsK",
            "E2NsaWVudF9yZWNlaXZlX3RpbWUYBSABKAMSGwoTc2VydmVyX3JlY2VpdmVf",
            "dGltZRgGIAEoAxIcChRzZXJ2ZXJfcmVzcG9uc2VfdGltZRgHIAEoA0IHWgUu",
            "LztwYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Empty), global::Pb.Empty.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Heartbeat), global::Pb.Heartbeat.Parser, new[]{ "SourceUid", "Time", "ReqTime", "ClientReqTime", "ClientReceiveTime", "ServerReceiveTime", "ServerResponseTime", "RequestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.FDCloseEvent), global::Pb.FDCloseEvent.Parser, new[]{ "SourceUid", "UserId", "Source", "ContentType", "ProtocolType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.FDCreateEvent), global::Pb.FDCreateEvent.Parser, new[]{ "SourceUid", "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.PingReq), global::Pb.PingReq.Parser, new[]{ "SourceUid", "RequestId", "TraceId", "ClientReqTime", "ClientReceiveTime", "ServerReceiveTime", "ServerResponseTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.PongRes), global::Pb.PongRes.Parser, new[]{ "SourceUid", "RequestId", "TraceId", "ClientReqTime", "ClientReceiveTime", "ServerReceiveTime", "ServerResponseTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///有些函数，没有返回值，统一定义一个，方便处理
  /// </summary>
  public sealed partial class Empty : pb::IMessage<Empty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  ///心跳，长连接保活。(不要与PING混淆)
  /// </summary>
  public sealed partial class Heartbeat : pb::IMessage<Heartbeat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Heartbeat> _parser = new pb::MessageParser<Heartbeat>(() => new Heartbeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Heartbeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat(Heartbeat other) : this() {
      sourceUid_ = other.sourceUid_;
      time_ = other.time_;
      reqTime_ = other.reqTime_;
      clientReqTime_ = other.clientReqTime_;
      clientReceiveTime_ = other.clientReceiveTime_;
      serverReceiveTime_ = other.serverReceiveTime_;
      serverResponseTime_ = other.serverResponseTime_;
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat Clone() {
      return new Heartbeat(this);
    }

    /// <summary>Field number for the "source_uid" field.</summary>
    public const int SourceUidFieldNumber = 1;
    private int sourceUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceUid {
      get { return sourceUid_; }
      set {
        sourceUid_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private long time_;
    /// <summary>
    ///这个字段不用了，用下面的字段，但保留
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "req_time" field.</summary>
    public const int ReqTimeFieldNumber = 3;
    private long reqTime_;
    /// <summary>
    ///这个字段不用了，用下面的字段，但保留
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqTime {
      get { return reqTime_; }
      set {
        reqTime_ = value;
      }
    }

    /// <summary>Field number for the "client_req_time" field.</summary>
    public const int ClientReqTimeFieldNumber = 4;
    private long clientReqTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReqTime {
      get { return clientReqTime_; }
      set {
        clientReqTime_ = value;
      }
    }

    /// <summary>Field number for the "client_receive_time" field.</summary>
    public const int ClientReceiveTimeFieldNumber = 5;
    private long clientReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReceiveTime {
      get { return clientReceiveTime_; }
      set {
        clientReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_receive_time" field.</summary>
    public const int ServerReceiveTimeFieldNumber = 6;
    private long serverReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerReceiveTime {
      get { return serverReceiveTime_; }
      set {
        serverReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_response_time" field.</summary>
    public const int ServerResponseTimeFieldNumber = 7;
    private long serverResponseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerResponseTime {
      get { return serverResponseTime_; }
      set {
        serverResponseTime_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 8;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Heartbeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Heartbeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceUid != other.SourceUid) return false;
      if (Time != other.Time) return false;
      if (ReqTime != other.ReqTime) return false;
      if (ClientReqTime != other.ClientReqTime) return false;
      if (ClientReceiveTime != other.ClientReceiveTime) return false;
      if (ServerReceiveTime != other.ServerReceiveTime) return false;
      if (ServerResponseTime != other.ServerResponseTime) return false;
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceUid != 0) hash ^= SourceUid.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (ReqTime != 0L) hash ^= ReqTime.GetHashCode();
      if (ClientReqTime != 0L) hash ^= ClientReqTime.GetHashCode();
      if (ClientReceiveTime != 0L) hash ^= ClientReceiveTime.GetHashCode();
      if (ServerReceiveTime != 0L) hash ^= ServerReceiveTime.GetHashCode();
      if (ServerResponseTime != 0L) hash ^= ServerResponseTime.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (ReqTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ReqTime);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (ReqTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ReqTime);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceUid);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (ReqTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqTime);
      }
      if (ClientReqTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerResponseTime);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Heartbeat other) {
      if (other == null) {
        return;
      }
      if (other.SourceUid != 0) {
        SourceUid = other.SourceUid;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.ReqTime != 0L) {
        ReqTime = other.ReqTime;
      }
      if (other.ClientReqTime != 0L) {
        ClientReqTime = other.ClientReqTime;
      }
      if (other.ClientReceiveTime != 0L) {
        ClientReceiveTime = other.ClientReceiveTime;
      }
      if (other.ServerReceiveTime != 0L) {
        ServerReceiveTime = other.ServerReceiveTime;
      }
      if (other.ServerResponseTime != 0L) {
        ServerResponseTime = other.ServerResponseTime;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
          case 24: {
            ReqTime = input.ReadInt64();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
          case 66: {
            RequestId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
          case 24: {
            ReqTime = input.ReadInt64();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
          case 66: {
            RequestId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FDCloseEvent : pb::IMessage<FDCloseEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FDCloseEvent> _parser = new pb::MessageParser<FDCloseEvent>(() => new FDCloseEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FDCloseEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCloseEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCloseEvent(FDCloseEvent other) : this() {
      sourceUid_ = other.sourceUid_;
      userId_ = other.userId_;
      source_ = other.source_;
      contentType_ = other.contentType_;
      protocolType_ = other.protocolType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCloseEvent Clone() {
      return new FDCloseEvent(this);
    }

    /// <summary>Field number for the "source_uid" field.</summary>
    public const int SourceUidFieldNumber = 1;
    private int sourceUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceUid {
      get { return sourceUid_; }
      set {
        sourceUid_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private int userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 3;
    private int source_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "content_type" field.</summary>
    public const int ContentTypeFieldNumber = 4;
    private int contentType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ContentType {
      get { return contentType_; }
      set {
        contentType_ = value;
      }
    }

    /// <summary>Field number for the "protocol_type" field.</summary>
    public const int ProtocolTypeFieldNumber = 5;
    private int protocolType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProtocolType {
      get { return protocolType_; }
      set {
        protocolType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FDCloseEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FDCloseEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceUid != other.SourceUid) return false;
      if (UserId != other.UserId) return false;
      if (Source != other.Source) return false;
      if (ContentType != other.ContentType) return false;
      if (ProtocolType != other.ProtocolType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceUid != 0) hash ^= SourceUid.GetHashCode();
      if (UserId != 0) hash ^= UserId.GetHashCode();
      if (Source != 0) hash ^= Source.GetHashCode();
      if (ContentType != 0) hash ^= ContentType.GetHashCode();
      if (ProtocolType != 0) hash ^= ProtocolType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (UserId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserId);
      }
      if (Source != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Source);
      }
      if (ContentType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ContentType);
      }
      if (ProtocolType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ProtocolType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (UserId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserId);
      }
      if (Source != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Source);
      }
      if (ContentType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ContentType);
      }
      if (ProtocolType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ProtocolType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceUid);
      }
      if (UserId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
      }
      if (Source != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Source);
      }
      if (ContentType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ContentType);
      }
      if (ProtocolType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtocolType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FDCloseEvent other) {
      if (other == null) {
        return;
      }
      if (other.SourceUid != 0) {
        SourceUid = other.SourceUid;
      }
      if (other.UserId != 0) {
        UserId = other.UserId;
      }
      if (other.Source != 0) {
        Source = other.Source;
      }
      if (other.ContentType != 0) {
        ContentType = other.ContentType;
      }
      if (other.ProtocolType != 0) {
        ProtocolType = other.ProtocolType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            UserId = input.ReadInt32();
            break;
          }
          case 24: {
            Source = input.ReadInt32();
            break;
          }
          case 32: {
            ContentType = input.ReadInt32();
            break;
          }
          case 40: {
            ProtocolType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            UserId = input.ReadInt32();
            break;
          }
          case 24: {
            Source = input.ReadInt32();
            break;
          }
          case 32: {
            ContentType = input.ReadInt32();
            break;
          }
          case 40: {
            ProtocolType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FDCreateEvent : pb::IMessage<FDCreateEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FDCreateEvent> _parser = new pb::MessageParser<FDCreateEvent>(() => new FDCreateEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FDCreateEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCreateEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCreateEvent(FDCreateEvent other) : this() {
      sourceUid_ = other.sourceUid_;
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FDCreateEvent Clone() {
      return new FDCreateEvent(this);
    }

    /// <summary>Field number for the "source_uid" field.</summary>
    public const int SourceUidFieldNumber = 1;
    private int sourceUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceUid {
      get { return sourceUid_; }
      set {
        sourceUid_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private int userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FDCreateEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FDCreateEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceUid != other.SourceUid) return false;
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceUid != 0) hash ^= SourceUid.GetHashCode();
      if (UserId != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (UserId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (UserId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceUid);
      }
      if (UserId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FDCreateEvent other) {
      if (other == null) {
        return;
      }
      if (other.SourceUid != 0) {
        SourceUid = other.SourceUid;
      }
      if (other.UserId != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            UserId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 16: {
            UserId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PingReq : pb::IMessage<PingReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PingReq> _parser = new pb::MessageParser<PingReq>(() => new PingReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PingReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PingReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PingReq(PingReq other) : this() {
      sourceUid_ = other.sourceUid_;
      requestId_ = other.requestId_;
      traceId_ = other.traceId_;
      clientReqTime_ = other.clientReqTime_;
      clientReceiveTime_ = other.clientReceiveTime_;
      serverReceiveTime_ = other.serverReceiveTime_;
      serverResponseTime_ = other.serverResponseTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PingReq Clone() {
      return new PingReq(this);
    }

    /// <summary>Field number for the "source_uid" field.</summary>
    public const int SourceUidFieldNumber = 1;
    private int sourceUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceUid {
      get { return sourceUid_; }
      set {
        sourceUid_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "trace_id" field.</summary>
    public const int TraceIdFieldNumber = 3;
    private string traceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TraceId {
      get { return traceId_; }
      set {
        traceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_req_time" field.</summary>
    public const int ClientReqTimeFieldNumber = 4;
    private long clientReqTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReqTime {
      get { return clientReqTime_; }
      set {
        clientReqTime_ = value;
      }
    }

    /// <summary>Field number for the "client_receive_time" field.</summary>
    public const int ClientReceiveTimeFieldNumber = 5;
    private long clientReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReceiveTime {
      get { return clientReceiveTime_; }
      set {
        clientReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_receive_time" field.</summary>
    public const int ServerReceiveTimeFieldNumber = 6;
    private long serverReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerReceiveTime {
      get { return serverReceiveTime_; }
      set {
        serverReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_response_time" field.</summary>
    public const int ServerResponseTimeFieldNumber = 7;
    private long serverResponseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerResponseTime {
      get { return serverResponseTime_; }
      set {
        serverResponseTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PingReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PingReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceUid != other.SourceUid) return false;
      if (RequestId != other.RequestId) return false;
      if (TraceId != other.TraceId) return false;
      if (ClientReqTime != other.ClientReqTime) return false;
      if (ClientReceiveTime != other.ClientReceiveTime) return false;
      if (ServerReceiveTime != other.ServerReceiveTime) return false;
      if (ServerResponseTime != other.ServerResponseTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceUid != 0) hash ^= SourceUid.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (TraceId.Length != 0) hash ^= TraceId.GetHashCode();
      if (ClientReqTime != 0L) hash ^= ClientReqTime.GetHashCode();
      if (ClientReceiveTime != 0L) hash ^= ClientReceiveTime.GetHashCode();
      if (ServerReceiveTime != 0L) hash ^= ServerReceiveTime.GetHashCode();
      if (ServerResponseTime != 0L) hash ^= ServerResponseTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TraceId);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TraceId);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceUid);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (TraceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TraceId);
      }
      if (ClientReqTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerResponseTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PingReq other) {
      if (other == null) {
        return;
      }
      if (other.SourceUid != 0) {
        SourceUid = other.SourceUid;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.TraceId.Length != 0) {
        TraceId = other.TraceId;
      }
      if (other.ClientReqTime != 0L) {
        ClientReqTime = other.ClientReqTime;
      }
      if (other.ClientReceiveTime != 0L) {
        ClientReceiveTime = other.ClientReceiveTime;
      }
      if (other.ServerReceiveTime != 0L) {
        ServerReceiveTime = other.ServerReceiveTime;
      }
      if (other.ServerResponseTime != 0L) {
        ServerResponseTime = other.ServerResponseTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            TraceId = input.ReadString();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            TraceId = input.ReadString();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PongRes : pb::IMessage<PongRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PongRes> _parser = new pb::MessageParser<PongRes>(() => new PongRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PongRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CommonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PongRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PongRes(PongRes other) : this() {
      sourceUid_ = other.sourceUid_;
      requestId_ = other.requestId_;
      traceId_ = other.traceId_;
      clientReqTime_ = other.clientReqTime_;
      clientReceiveTime_ = other.clientReceiveTime_;
      serverReceiveTime_ = other.serverReceiveTime_;
      serverResponseTime_ = other.serverResponseTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PongRes Clone() {
      return new PongRes(this);
    }

    /// <summary>Field number for the "source_uid" field.</summary>
    public const int SourceUidFieldNumber = 1;
    private int sourceUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceUid {
      get { return sourceUid_; }
      set {
        sourceUid_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "trace_id" field.</summary>
    public const int TraceIdFieldNumber = 3;
    private string traceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TraceId {
      get { return traceId_; }
      set {
        traceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_req_time" field.</summary>
    public const int ClientReqTimeFieldNumber = 4;
    private long clientReqTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReqTime {
      get { return clientReqTime_; }
      set {
        clientReqTime_ = value;
      }
    }

    /// <summary>Field number for the "client_receive_time" field.</summary>
    public const int ClientReceiveTimeFieldNumber = 5;
    private long clientReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientReceiveTime {
      get { return clientReceiveTime_; }
      set {
        clientReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_receive_time" field.</summary>
    public const int ServerReceiveTimeFieldNumber = 6;
    private long serverReceiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerReceiveTime {
      get { return serverReceiveTime_; }
      set {
        serverReceiveTime_ = value;
      }
    }

    /// <summary>Field number for the "server_response_time" field.</summary>
    public const int ServerResponseTimeFieldNumber = 7;
    private long serverResponseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerResponseTime {
      get { return serverResponseTime_; }
      set {
        serverResponseTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PongRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PongRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceUid != other.SourceUid) return false;
      if (RequestId != other.RequestId) return false;
      if (TraceId != other.TraceId) return false;
      if (ClientReqTime != other.ClientReqTime) return false;
      if (ClientReceiveTime != other.ClientReceiveTime) return false;
      if (ServerReceiveTime != other.ServerReceiveTime) return false;
      if (ServerResponseTime != other.ServerResponseTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceUid != 0) hash ^= SourceUid.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (TraceId.Length != 0) hash ^= TraceId.GetHashCode();
      if (ClientReqTime != 0L) hash ^= ClientReqTime.GetHashCode();
      if (ClientReceiveTime != 0L) hash ^= ClientReceiveTime.GetHashCode();
      if (ServerReceiveTime != 0L) hash ^= ServerReceiveTime.GetHashCode();
      if (ServerResponseTime != 0L) hash ^= ServerResponseTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TraceId);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceUid);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TraceId);
      }
      if (ClientReqTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ServerResponseTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceUid);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (TraceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TraceId);
      }
      if (ClientReqTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReqTime);
      }
      if (ClientReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientReceiveTime);
      }
      if (ServerReceiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerReceiveTime);
      }
      if (ServerResponseTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerResponseTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PongRes other) {
      if (other == null) {
        return;
      }
      if (other.SourceUid != 0) {
        SourceUid = other.SourceUid;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.TraceId.Length != 0) {
        TraceId = other.TraceId;
      }
      if (other.ClientReqTime != 0L) {
        ClientReqTime = other.ClientReqTime;
      }
      if (other.ClientReceiveTime != 0L) {
        ClientReceiveTime = other.ClientReceiveTime;
      }
      if (other.ServerReceiveTime != 0L) {
        ServerReceiveTime = other.ServerReceiveTime;
      }
      if (other.ServerResponseTime != 0L) {
        ServerResponseTime = other.ServerResponseTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            TraceId = input.ReadString();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceUid = input.ReadInt32();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            TraceId = input.ReadString();
            break;
          }
          case 32: {
            ClientReqTime = input.ReadInt64();
            break;
          }
          case 40: {
            ClientReceiveTime = input.ReadInt64();
            break;
          }
          case 48: {
            ServerReceiveTime = input.ReadInt64();
            break;
          }
          case 56: {
            ServerResponseTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
